// GENERATED by scripts/build-nutrients.mts from USDA FoodData Central SR Legacy.
// Do not edit by hand — run `npm run build:nutrients -- --emit`.
// Every entry records the fdc_id it came from, so every nutrient value is traceable.

export interface Per100g {
  cal?: number; protein?: number; carbs?: number; fat?: number; fiber?: number;
  calcium?: number; iron?: number; magnesium?: number; potassium?: number; sodium?: number;
  zinc?: number; vitD?: number; vitC?: number; folate?: number; b12?: number;
}

export const NUTRIENT_TABLE: Record<string, { fdcId: number; desc: string; per100g: Per100g }> = {
  "brown rice": {
    "fdcId": 169703,
    "desc": "Rice, brown, long-grain, raw (Includes foods for USDA's Food Distribution Program)",
    "per100g": {
      "calcium": 9,
      "potassium": 250,
      "zinc": 2.13,
      "fat": 3.2,
      "carbs": 76.25,
      "cal": 367,
      "fiber": 3.6,
      "iron": 1.29,
      "magnesium": 116,
      "sodium": 5,
      "protein": 7.54,
      "folate": 23,
      "b12": 0,
      "vitC": 0,
      "vitD": 0
    }
  },
  "rice": {
    "fdcId": 169756,
    "desc": "Rice, white, long-grain, regular, raw, unenriched",
    "per100g": {
      "protein": 7.13,
      "fiber": 1.3,
      "iron": 0.8,
      "magnesium": 25,
      "sodium": 5,
      "vitC": 0,
      "folate": 8,
      "b12": 0,
      "fat": 0.66,
      "carbs": 79.95,
      "cal": 365,
      "calcium": 28,
      "potassium": 115,
      "zinc": 1.09,
      "vitD": 0
    }
  },
  "cooked rice": {
    "fdcId": 169704,
    "desc": "Rice, brown, long-grain, cooked (Includes foods for USDA's Food Distribution Program)",
    "per100g": {
      "fiber": 1.6,
      "iron": 0.56,
      "magnesium": 39,
      "sodium": 4,
      "folate": 9,
      "protein": 2.74,
      "fat": 0.97,
      "carbs": 25.58,
      "cal": 123,
      "calcium": 3,
      "potassium": 86,
      "zinc": 0.71,
      "vitC": 0,
      "b12": 0,
      "vitD": 0
    }
  },
  "quinoa": {
    "fdcId": 168874,
    "desc": "Quinoa, uncooked",
    "per100g": {
      "fiber": 7,
      "iron": 4.57,
      "magnesium": 197,
      "sodium": 5,
      "folate": 184,
      "protein": 14.12,
      "fat": 6.07,
      "calcium": 47,
      "potassium": 563,
      "zinc": 3.1,
      "carbs": 64.16,
      "cal": 368,
      "b12": 0,
      "vitD": 0
    }
  },
  "bulgur": {
    "fdcId": 170688,
    "desc": "Bulgur, dry",
    "per100g": {
      "fiber": 12.5,
      "calcium": 35,
      "potassium": 410,
      "zinc": 1.93,
      "fat": 1.33,
      "carbs": 75.87,
      "cal": 342,
      "vitC": 0,
      "folate": 27,
      "b12": 0,
      "protein": 12.29,
      "iron": 2.46,
      "magnesium": 164,
      "sodium": 17,
      "vitD": 0
    }
  },
  "couscous": {
    "fdcId": 169699,
    "desc": "Couscous, dry",
    "per100g": {
      "fiber": 5,
      "iron": 1.08,
      "magnesium": 44,
      "sodium": 10,
      "vitC": 0,
      "folate": 20,
      "b12": 0,
      "protein": 12.76,
      "fat": 0.64,
      "carbs": 77.43,
      "cal": 376,
      "calcium": 24,
      "potassium": 166,
      "zinc": 0.83,
      "vitD": 0
    }
  },
  "rolled oats": {
    "fdcId": 173904,
    "desc": "Cereals, oats, regular and quick, not fortified, dry",
    "per100g": {
      "vitC": 0,
      "fiber": 10.1,
      "iron": 4.25,
      "magnesium": 138,
      "potassium": 362,
      "zinc": 3.64,
      "fat": 6.52,
      "carbs": 67.7,
      "cal": 379,
      "calcium": 52,
      "sodium": 6,
      "folate": 32,
      "protein": 13.15,
      "vitD": 0,
      "b12": 0
    }
  },
  "oat flour": {
    "fdcId": 169741,
    "desc": "Oat flour, partially debranned",
    "per100g": {
      "carbs": 65.7,
      "cal": 404,
      "b12": 0,
      "protein": 14.66,
      "fiber": 6.5,
      "iron": 4,
      "magnesium": 144,
      "sodium": 19,
      "fat": 9.12,
      "calcium": 55,
      "potassium": 371,
      "zinc": 3.2,
      "folate": 32,
      "vitC": 0,
      "vitD": 0
    }
  },
  "muesli": {
    "fdcId": 171646,
    "desc": "Cereals ready-to-eat, granola, homemade",
    "per100g": {
      "vitC": 1.2,
      "b12": 0,
      "fat": 24.31,
      "carbs": 53.88,
      "calcium": 76,
      "potassium": 539,
      "zinc": 4.17,
      "vitD": 0,
      "protein": 13.67,
      "folate": 84,
      "fiber": 8.9,
      "iron": 3.95,
      "magnesium": 168,
      "sodium": 26,
      "cal": 489
    }
  },
  "granola": {
    "fdcId": 171646,
    "desc": "Cereals ready-to-eat, granola, homemade",
    "per100g": {
      "vitC": 1.2,
      "b12": 0,
      "fat": 24.31,
      "carbs": 53.88,
      "calcium": 76,
      "potassium": 539,
      "zinc": 4.17,
      "vitD": 0,
      "protein": 13.67,
      "folate": 84,
      "fiber": 8.9,
      "iron": 3.95,
      "magnesium": 168,
      "sodium": 26,
      "cal": 489
    }
  },
  "whole-wheat pasta": {
    "fdcId": 169738,
    "desc": "Pasta, whole-wheat, dry (Includes foods for USDA's Food Distribution Program)",
    "per100g": {
      "folate": 69,
      "protein": 13.87,
      "fiber": 9.2,
      "iron": 3.62,
      "magnesium": 128,
      "sodium": 6,
      "fat": 2.93,
      "carbs": 73.37,
      "cal": 352,
      "calcium": 29,
      "potassium": 434,
      "zinc": 2.97,
      "b12": 0,
      "vitD": 0
    }
  },
  "whole-wheat penne": {
    "fdcId": 169738,
    "desc": "Pasta, whole-wheat, dry (Includes foods for USDA's Food Distribution Program)",
    "per100g": {
      "folate": 69,
      "protein": 13.87,
      "fiber": 9.2,
      "iron": 3.62,
      "magnesium": 128,
      "sodium": 6,
      "fat": 2.93,
      "carbs": 73.37,
      "cal": 352,
      "calcium": 29,
      "potassium": 434,
      "zinc": 2.97,
      "b12": 0,
      "vitD": 0
    }
  },
  "whole-wheat spaghetti": {
    "fdcId": 169738,
    "desc": "Pasta, whole-wheat, dry (Includes foods for USDA's Food Distribution Program)",
    "per100g": {
      "folate": 69,
      "protein": 13.87,
      "fiber": 9.2,
      "iron": 3.62,
      "magnesium": 128,
      "sodium": 6,
      "fat": 2.93,
      "carbs": 73.37,
      "cal": 352,
      "calcium": 29,
      "potassium": 434,
      "zinc": 2.97,
      "b12": 0,
      "vitD": 0
    }
  },
  "orzo": {
    "fdcId": 169736,
    "desc": "Pasta, dry, enriched",
    "per100g": {
      "magnesium": 53,
      "sodium": 6,
      "calcium": 21,
      "potassium": 223,
      "zinc": 1.41,
      "iron": 3.3,
      "carbs": 74.67,
      "cal": 371,
      "vitC": 0,
      "b12": 0,
      "fat": 1.51,
      "fiber": 3.2,
      "folate": 237,
      "protein": 13.04,
      "vitD": 0
    }
  },
  "egg noodles": {
    "fdcId": 169731,
    "desc": "Noodles, egg, dry, enriched",
    "per100g": {
      "carbs": 71.27,
      "cal": 384,
      "vitD": 0.3,
      "iron": 4.01,
      "folate": 230,
      "b12": 0.29,
      "vitC": 0,
      "fiber": 3.3,
      "magnesium": 58,
      "sodium": 21,
      "protein": 14.16,
      "fat": 4.44,
      "calcium": 35,
      "potassium": 244,
      "zinc": 1.92
    }
  },
  "soba noodles": {
    "fdcId": 168906,
    "desc": "Noodles, japanese, soba, dry",
    "per100g": {
      "folate": 60,
      "b12": 0,
      "protein": 14.38,
      "vitC": 0,
      "iron": 2.7,
      "magnesium": 95,
      "sodium": 792,
      "fat": 0.71,
      "carbs": 74.62,
      "cal": 336,
      "calcium": 35,
      "potassium": 252,
      "zinc": 1.71,
      "vitD": 0
    }
  },
  "rice noodles": {
    "fdcId": 169742,
    "desc": "Rice noodles, dry",
    "per100g": {
      "vitD": 0,
      "fat": 0.56,
      "cal": 364,
      "calcium": 18,
      "potassium": 30,
      "zinc": 0.74,
      "vitC": 0,
      "folate": 3,
      "b12": 0,
      "fiber": 1.6,
      "iron": 0.7,
      "magnesium": 12,
      "sodium": 182,
      "protein": 5.95,
      "carbs": 80.18
    }
  },
  "panko": {
    "fdcId": 174928,
    "desc": "Bread, crumbs, dry, grated, plain",
    "per100g": {
      "calcium": 183,
      "potassium": 196,
      "zinc": 1.45,
      "fat": 5.3,
      "protein": 13.35,
      "fiber": 4.5,
      "iron": 4.83,
      "magnesium": 43,
      "sodium": 732,
      "folate": 107,
      "b12": 0.35,
      "carbs": 71.98,
      "cal": 395,
      "vitC": 0,
      "vitD": 0
    }
  },
  "chickpea flour": {
    "fdcId": 174288,
    "desc": "Chickpea flour (besan)",
    "per100g": {
      "carbs": 57.82,
      "cal": 387,
      "vitD": 0,
      "protein": 22.39,
      "vitC": 0,
      "folate": 437,
      "b12": 0,
      "fiber": 10.8,
      "iron": 4.86,
      "magnesium": 166,
      "sodium": 64,
      "fat": 6.69,
      "calcium": 45,
      "potassium": 846,
      "zinc": 2.81
    }
  },
  "chicken breast": {
    "fdcId": 171077,
    "desc": "Chicken, broiler or fryers, breast, skinless, boneless, meat only, raw",
    "per100g": {
      "calcium": 5,
      "iron": 0.37,
      "potassium": 334,
      "zinc": 0.68,
      "fat": 2.62,
      "cal": 120,
      "vitC": 0,
      "magnesium": 28,
      "sodium": 45,
      "protein": 22.5,
      "b12": 0.21,
      "folate": 9,
      "carbs": 0,
      "fiber": 0,
      "vitD": 0
    }
  },
  "chicken thigh": {
    "fdcId": 173627,
    "desc": "Chicken, broilers or fryers, dark meat, thigh, meat only, raw",
    "per100g": {
      "calcium": 7,
      "potassium": 242,
      "zinc": 1.58,
      "cal": 121,
      "fat": 4.12,
      "sodium": 95,
      "protein": 19.66,
      "iron": 0.81,
      "b12": 0.61,
      "folate": 4,
      "magnesium": 23,
      "vitD": 0,
      "carbs": 0,
      "fiber": 0,
      "vitC": 0
    }
  },
  "turkey breast": {
    "fdcId": 171098,
    "desc": "Turkey, whole, breast, meat only, raw",
    "per100g": {
      "cal": 114,
      "calcium": 11,
      "potassium": 242,
      "zinc": 1.28,
      "fat": 1.48,
      "protein": 23.66,
      "sodium": 113,
      "vitD": 0.1,
      "folate": 7,
      "b12": 0.63,
      "iron": 0.73,
      "carbs": 0.14,
      "magnesium": 28,
      "fiber": 0,
      "vitC": 0
    }
  },
  "ground turkey": {
    "fdcId": 172850,
    "desc": "Turkey, ground, 93% lean, 7% fat, raw",
    "per100g": {
      "fiber": 0,
      "iron": 1.17,
      "magnesium": 21,
      "sodium": 69,
      "vitD": 0.4,
      "vitC": 0,
      "folate": 7,
      "b12": 1.2,
      "protein": 18.73,
      "fat": 8.34,
      "calcium": 21,
      "potassium": 213,
      "zinc": 2.53,
      "carbs": 0,
      "cal": 150
    }
  },
  "turkey sausage": {
    "fdcId": 174617,
    "desc": "Sausage, turkey, fresh, raw",
    "per100g": {
      "fat": 8.08,
      "calcium": 19,
      "potassium": 262,
      "zinc": 3.06,
      "protein": 18.79,
      "b12": 1.3,
      "fiber": 0,
      "iron": 1.17,
      "magnesium": 19,
      "sodium": 593,
      "vitC": 2.3,
      "carbs": 0.47,
      "cal": 155,
      "folate": 5
    }
  },
  "lean beef": {
    "fdcId": 171758,
    "desc": "Beef, round, top round steak, boneless, separable lean only, trimmed to 0\" fat, choice, raw",
    "per100g": {
      "fat": 3.26,
      "carbs": 0,
      "cal": 124,
      "calcium": 13,
      "potassium": 309,
      "zinc": 3.78,
      "protein": 23.59,
      "fiber": 0,
      "iron": 2.35,
      "magnesium": 12,
      "sodium": 56,
      "vitD": 0,
      "vitC": 0,
      "folate": 4,
      "b12": 1.66
    }
  },
  "lean steak": {
    "fdcId": 171758,
    "desc": "Beef, round, top round steak, boneless, separable lean only, trimmed to 0\" fat, choice, raw",
    "per100g": {
      "fat": 3.26,
      "carbs": 0,
      "cal": 124,
      "calcium": 13,
      "potassium": 309,
      "zinc": 3.78,
      "protein": 23.59,
      "fiber": 0,
      "iron": 2.35,
      "magnesium": 12,
      "sodium": 56,
      "vitD": 0,
      "vitC": 0,
      "folate": 4,
      "b12": 1.66
    }
  },
  "beef strips": {
    "fdcId": 171758,
    "desc": "Beef, round, top round steak, boneless, separable lean only, trimmed to 0\" fat, choice, raw",
    "per100g": {
      "fat": 3.26,
      "carbs": 0,
      "cal": 124,
      "calcium": 13,
      "potassium": 309,
      "zinc": 3.78,
      "protein": 23.59,
      "fiber": 0,
      "iron": 2.35,
      "magnesium": 12,
      "sodium": 56,
      "vitD": 0,
      "vitC": 0,
      "folate": 4,
      "b12": 1.66
    }
  },
  "lean ground beef": {
    "fdcId": 173110,
    "desc": "Beef, ground, 93% lean meat / 7% fat, raw",
    "per100g": {
      "fat": 7,
      "carbs": 0,
      "calcium": 10,
      "potassium": 336,
      "zinc": 4.97,
      "protein": 20.85,
      "fiber": 0,
      "iron": 2.33,
      "magnesium": 21,
      "sodium": 66,
      "vitC": 0,
      "folate": 5,
      "b12": 2.23,
      "vitD": 0.1,
      "cal": 152
    }
  },
  "lean roast beef": {
    "fdcId": 171770,
    "desc": "Beef, round, top round roast, boneless, separable lean only, trimmed to 0\" fat, choice, cooked, roasted",
    "per100g": {
      "calcium": 16,
      "potassium": 381,
      "zinc": 4.67,
      "vitC": 0,
      "folate": 5,
      "b12": 2.05,
      "fiber": 0,
      "iron": 2.91,
      "magnesium": 15,
      "sodium": 69,
      "vitD": 0,
      "protein": 30.24,
      "fat": 4.11,
      "carbs": 0.06,
      "cal": 158
    }
  },
  "pork tenderloin": {
    "fdcId": 168249,
    "desc": "Pork, fresh, loin, tenderloin, separable lean only, raw",
    "per100g": {
      "calcium": 5,
      "potassium": 399,
      "zinc": 1.89,
      "fat": 2.17,
      "vitC": 0,
      "folate": 0,
      "b12": 0.51,
      "iron": 0.98,
      "magnesium": 27,
      "sodium": 53,
      "protein": 20.95,
      "cal": 109,
      "vitD": 0.2,
      "carbs": 0,
      "fiber": 0
    }
  },
  "lean pork sausage": {
    "fdcId": 171631,
    "desc": "Sausage, Italian, pork, mild, raw",
    "per100g": {
      "fiber": 0,
      "b12": 1,
      "magnesium": 16,
      "sodium": 563,
      "iron": 1.77,
      "protein": 13.9,
      "vitC": 0,
      "calcium": 12,
      "potassium": 211,
      "zinc": 1.91,
      "fat": 24.26,
      "carbs": 2.97,
      "cal": 290
    }
  },
  "salmon fillet": {
    "fdcId": 175167,
    "desc": "Fish, salmon, Atlantic, farmed, raw",
    "per100g": {
      "cal": 208,
      "calcium": 9,
      "potassium": 363,
      "zinc": 0.36,
      "fat": 13.42,
      "b12": 3.23,
      "protein": 20.42,
      "iron": 0.34,
      "magnesium": 27,
      "sodium": 59,
      "vitD": 11,
      "fiber": 0,
      "vitC": 3.9,
      "folate": 26,
      "carbs": 0
    }
  },
  "smoked salmon": {
    "fdcId": 173687,
    "desc": "Fish, salmon, chinook, smoked",
    "per100g": {
      "vitD": 17.1,
      "sodium": 672,
      "calcium": 11,
      "potassium": 175,
      "zinc": 0.31,
      "fat": 4.32,
      "carbs": 0,
      "cal": 117,
      "protein": 18.28,
      "fiber": 0,
      "iron": 0.85,
      "magnesium": 18,
      "vitC": 0,
      "folate": 2,
      "b12": 3.26
    }
  },
  "cod fillet": {
    "fdcId": 171955,
    "desc": "Fish, cod, Atlantic, raw",
    "per100g": {
      "cal": 82,
      "vitD": 0.9,
      "fiber": 0,
      "iron": 0.38,
      "magnesium": 32,
      "sodium": 54,
      "vitC": 1,
      "folate": 7,
      "b12": 0.91,
      "protein": 17.81,
      "fat": 0.67,
      "carbs": 0,
      "calcium": 16,
      "potassium": 413,
      "zinc": 0.45
    }
  },
  "canned tuna": {
    "fdcId": 173709,
    "desc": "Fish, tuna, light, canned in water, drained solids (Includes foods for USDA's Food Distribution Program)",
    "per100g": {
      "calcium": 17,
      "potassium": 179,
      "zinc": 0.69,
      "fat": 0.96,
      "cal": 86,
      "vitD": 1.2,
      "b12": 2.55,
      "protein": 19.44,
      "iron": 1.63,
      "magnesium": 23,
      "sodium": 247,
      "vitC": 0,
      "folate": 4,
      "fiber": 0,
      "carbs": 0
    }
  },
  "smoked mackerel": {
    "fdcId": 175119,
    "desc": "Fish, mackerel, Atlantic, raw",
    "per100g": {
      "vitD": 16.1,
      "fat": 13.89,
      "carbs": 0,
      "cal": 205,
      "calcium": 12,
      "potassium": 314,
      "zinc": 0.63,
      "protein": 18.6,
      "fiber": 0,
      "iron": 1.63,
      "magnesium": 76,
      "sodium": 90,
      "vitC": 0.4,
      "folate": 1,
      "b12": 8.71
    }
  },
  "smoked trout": {
    "fdcId": 173717,
    "desc": "Fish, trout, rainbow, farmed, raw",
    "per100g": {
      "fat": 6.18,
      "potassium": 377,
      "zinc": 0.45,
      "cal": 141,
      "calcium": 25,
      "protein": 19.94,
      "b12": 4.3,
      "sodium": 51,
      "vitD": 15.9,
      "iron": 0.31,
      "magnesium": 25,
      "folate": 11,
      "vitC": 2.9,
      "fiber": 0,
      "carbs": 0
    }
  },
  "shrimp": {
    "fdcId": 175179,
    "desc": "Crustaceans, shrimp, raw",
    "per100g": {
      "fat": 0.51,
      "carbs": 0,
      "cal": 85,
      "calcium": 64,
      "potassium": 264,
      "zinc": 1.34,
      "protein": 20.1,
      "iron": 0.52,
      "magnesium": 35,
      "sodium": 119
    }
  },
  "prawns": {
    "fdcId": 175179,
    "desc": "Crustaceans, shrimp, raw",
    "per100g": {
      "fat": 0.51,
      "carbs": 0,
      "cal": 85,
      "calcium": 64,
      "potassium": 264,
      "zinc": 1.34,
      "protein": 20.1,
      "iron": 0.52,
      "magnesium": 35,
      "sodium": 119
    }
  },
  "eggs": {
    "fdcId": 171287,
    "desc": "Egg, whole, raw, fresh",
    "per100g": {
      "cal": 143,
      "b12": 0.89,
      "protein": 12.56,
      "iron": 1.75,
      "magnesium": 12,
      "sodium": 142,
      "calcium": 56,
      "potassium": 138,
      "zinc": 1.29,
      "fat": 9.51,
      "carbs": 0.72,
      "vitD": 2,
      "folate": 47,
      "vitC": 0,
      "fiber": 0
    }
  },
  "egg": {
    "fdcId": 171287,
    "desc": "Egg, whole, raw, fresh",
    "per100g": {
      "cal": 143,
      "b12": 0.89,
      "protein": 12.56,
      "iron": 1.75,
      "magnesium": 12,
      "sodium": 142,
      "calcium": 56,
      "potassium": 138,
      "zinc": 1.29,
      "fat": 9.51,
      "carbs": 0.72,
      "vitD": 2,
      "folate": 47,
      "vitC": 0,
      "fiber": 0
    }
  },
  "egg whites": {
    "fdcId": 172183,
    "desc": "Egg, white, raw, fresh",
    "per100g": {
      "vitC": 0,
      "fiber": 0,
      "folate": 4,
      "b12": 0.09,
      "iron": 0.08,
      "magnesium": 11,
      "sodium": 166,
      "protein": 10.9,
      "calcium": 7,
      "potassium": 163,
      "zinc": 0.03,
      "fat": 0.17,
      "cal": 52,
      "vitD": 0,
      "carbs": 0.73
    }
  },
  "firm tofu": {
    "fdcId": 172448,
    "desc": "Tofu, firm, prepared with calcium sulfate and magnesium chloride (nigari)",
    "per100g": {
      "fiber": 0.9,
      "protein": 9.04,
      "carbs": 2.85,
      "cal": 78,
      "vitD": 0,
      "b12": 0,
      "vitC": 0.2,
      "calcium": 201,
      "potassium": 148,
      "zinc": 0.83,
      "fat": 4.17,
      "folate": 19,
      "iron": 1.61,
      "magnesium": 37,
      "sodium": 12
    }
  },
  "tempeh": {
    "fdcId": 174272,
    "desc": "Tempeh",
    "per100g": {
      "b12": 0.08,
      "protein": 20.29,
      "carbs": 7.64,
      "cal": 192,
      "iron": 2.7,
      "magnesium": 81,
      "sodium": 9,
      "vitC": 0,
      "folate": 24,
      "calcium": 111,
      "potassium": 412,
      "zinc": 1.14,
      "fat": 10.8,
      "vitD": 0
    }
  },
  "edamame": {
    "fdcId": 168411,
    "desc": "Edamame, frozen, prepared",
    "per100g": {
      "fat": 5.2,
      "fiber": 5.2,
      "vitC": 6.1,
      "folate": 311,
      "iron": 2.27,
      "magnesium": 64,
      "sodium": 6,
      "calcium": 63,
      "potassium": 436,
      "zinc": 1.37,
      "carbs": 8.91,
      "cal": 121,
      "protein": 11.91,
      "vitD": 0,
      "b12": 0
    }
  },
  "bean sprouts": {
    "fdcId": 169957,
    "desc": "Mung beans, mature seeds, sprouted, raw",
    "per100g": {
      "carbs": 5.94,
      "cal": 30,
      "protein": 3.04,
      "fiber": 1.8,
      "iron": 0.91,
      "magnesium": 21,
      "sodium": 6,
      "vitC": 13.2,
      "folate": 61,
      "b12": 0,
      "fat": 0.18,
      "calcium": 13,
      "potassium": 149,
      "zinc": 0.41,
      "vitD": 0
    }
  },
  "chickpeas": {
    "fdcId": 173800,
    "desc": "Chickpeas (garbanzo beans, bengal gram), mature seeds, canned, drained solids",
    "per100g": {
      "protein": 7.05,
      "iron": 1.07,
      "magnesium": 26,
      "sodium": 246,
      "vitD": 0,
      "vitC": 0.1,
      "folate": 48,
      "b12": 0,
      "calcium": 45,
      "potassium": 126,
      "zinc": 0.63,
      "fat": 2.77,
      "carbs": 22.53,
      "cal": 139,
      "fiber": 6.4
    }
  },
  "black beans": {
    "fdcId": 173735,
    "desc": "Beans, black, mature seeds, cooked, boiled, without salt",
    "per100g": {
      "vitD": 0,
      "calcium": 27,
      "potassium": 355,
      "zinc": 1.12,
      "fat": 0.54,
      "carbs": 23.71,
      "cal": 132,
      "protein": 8.86,
      "fiber": 8.7,
      "iron": 2.1,
      "magnesium": 70,
      "sodium": 1,
      "vitC": 0,
      "folate": 149,
      "b12": 0
    }
  },
  "kidney beans": {
    "fdcId": 173740,
    "desc": "Beans, kidney, all types, mature seeds, cooked, boiled, without salt",
    "per100g": {
      "calcium": 35,
      "potassium": 405,
      "zinc": 1,
      "iron": 2.22,
      "magnesium": 42,
      "sodium": 1,
      "b12": 0,
      "cal": 127,
      "fat": 0.5,
      "carbs": 22.8,
      "vitD": 0,
      "protein": 8.67,
      "fiber": 6.4,
      "vitC": 1.2,
      "folate": 130
    }
  },
  "cannellini beans": {
    "fdcId": 175203,
    "desc": "Beans, white, mature seeds, cooked, boiled, without salt",
    "per100g": {
      "carbs": 25.09,
      "cal": 139,
      "vitD": 0,
      "fiber": 6.3,
      "iron": 3.7,
      "magnesium": 63,
      "sodium": 6,
      "vitC": 0,
      "folate": 81,
      "b12": 0,
      "protein": 9.73,
      "fat": 0.35,
      "calcium": 90,
      "potassium": 561,
      "zinc": 1.38
    }
  },
  "lentils": {
    "fdcId": 172421,
    "desc": "Lentils, mature seeds, cooked, boiled, without salt",
    "per100g": {
      "carbs": 20.13,
      "cal": 116,
      "vitD": 0,
      "protein": 9.02,
      "fiber": 7.9,
      "iron": 3.33,
      "magnesium": 36,
      "sodium": 2,
      "vitC": 1.5,
      "folate": 181,
      "b12": 0,
      "fat": 0.38,
      "calcium": 19,
      "potassium": 369,
      "zinc": 1.27
    }
  },
  "green lentils": {
    "fdcId": 172421,
    "desc": "Lentils, mature seeds, cooked, boiled, without salt",
    "per100g": {
      "carbs": 20.13,
      "cal": 116,
      "vitD": 0,
      "protein": 9.02,
      "fiber": 7.9,
      "iron": 3.33,
      "magnesium": 36,
      "sodium": 2,
      "vitC": 1.5,
      "folate": 181,
      "b12": 0,
      "fat": 0.38,
      "calcium": 19,
      "potassium": 369,
      "zinc": 1.27
    }
  },
  "red lentils": {
    "fdcId": 172420,
    "desc": "Lentils, raw",
    "per100g": {
      "b12": 0,
      "fat": 1.06,
      "sodium": 6,
      "folate": 479,
      "fiber": 10.7,
      "iron": 6.51,
      "magnesium": 47,
      "protein": 24.63,
      "vitC": 4.5,
      "carbs": 63.35,
      "cal": 352,
      "calcium": 35,
      "potassium": 677,
      "zinc": 3.27,
      "vitD": 0
    }
  },
  "peas": {
    "fdcId": 170016,
    "desc": "Peas, green, frozen, unprepared (Includes foods for USDA's Food Distribution Program)",
    "per100g": {
      "calcium": 22,
      "potassium": 153,
      "zinc": 0.82,
      "fat": 0.4,
      "carbs": 13.62,
      "cal": 77,
      "protein": 5.22,
      "fiber": 4.5,
      "iron": 1.53,
      "magnesium": 26,
      "sodium": 108,
      "vitC": 18,
      "folate": 53,
      "b12": 0,
      "vitD": 0
    }
  },
  "corn": {
    "fdcId": 169214,
    "desc": "Corn, sweet, yellow, canned, whole kernel, drained solids",
    "per100g": {
      "fat": 1.22,
      "carbs": 14.34,
      "cal": 67,
      "potassium": 132,
      "zinc": 0.32,
      "vitC": 1.8,
      "fiber": 2,
      "iron": 0.27,
      "sodium": 205,
      "protein": 2.29,
      "folate": 39,
      "b12": 0,
      "calcium": 3,
      "magnesium": 13,
      "vitD": 0
    }
  },
  "greek yogurt": {
    "fdcId": 170894,
    "desc": "Yogurt, Greek, plain, nonfat (Includes foods for USDA's Food Distribution Program)",
    "per100g": {
      "magnesium": 11,
      "fiber": 0,
      "vitC": 0,
      "folate": 7,
      "b12": 0.75,
      "iron": 0.07,
      "protein": 10.19,
      "sodium": 36,
      "vitD": 0,
      "fat": 0.39,
      "carbs": 3.6,
      "cal": 59,
      "calcium": 110,
      "potassium": 141,
      "zinc": 0.52
    }
  },
  "yogurt": {
    "fdcId": 170886,
    "desc": "Yogurt, plain, low fat",
    "per100g": {
      "vitD": 0,
      "cal": 63,
      "calcium": 183,
      "potassium": 234,
      "zinc": 0.89,
      "fat": 1.55,
      "carbs": 7.04,
      "protein": 5.25,
      "fiber": 0,
      "iron": 0.08,
      "magnesium": 17,
      "sodium": 70,
      "vitC": 0.8,
      "folate": 11,
      "b12": 0.56
    }
  },
  "milk": {
    "fdcId": 171267,
    "desc": "Milk, reduced fat, fluid, 2% milkfat, with added vitamin A and vitamin D",
    "per100g": {
      "protein": 3.3,
      "vitC": 0.2,
      "fiber": 0,
      "vitD": 1.2,
      "carbs": 4.8,
      "cal": 50,
      "folate": 5,
      "calcium": 120,
      "potassium": 140,
      "zinc": 0.48,
      "fat": 1.98,
      "iron": 0.02,
      "magnesium": 11,
      "sodium": 47,
      "b12": 0.53
    }
  },
  "cottage cheese": {
    "fdcId": 172182,
    "desc": "Cheese, cottage, lowfat, 2% milkfat",
    "per100g": {
      "fat": 2.27,
      "carbs": 4.76,
      "cal": 81,
      "calcium": 111,
      "potassium": 125,
      "zinc": 0.51,
      "protein": 10.45,
      "folate": 8,
      "b12": 0.47,
      "iron": 0.13,
      "magnesium": 9,
      "sodium": 308,
      "vitC": 0,
      "fiber": 0,
      "vitD": 0
    }
  },
  "feta": {
    "fdcId": 173420,
    "desc": "Cheese, feta",
    "per100g": {
      "vitD": 0.4,
      "fat": 21.49,
      "carbs": 3.88,
      "cal": 265,
      "sodium": 1139,
      "calcium": 493,
      "potassium": 62,
      "zinc": 2.88,
      "protein": 14.21,
      "fiber": 0,
      "iron": 0.65,
      "magnesium": 19,
      "vitC": 0,
      "folate": 32,
      "b12": 1.69
    }
  },
  "cheddar": {
    "fdcId": 170899,
    "desc": "Cheese, cheddar, sharp, sliced",
    "per100g": {
      "protein": 24.25,
      "fiber": 0,
      "iron": 0.16,
      "magnesium": 27,
      "sodium": 644,
      "vitD": 1,
      "vitC": 0,
      "folate": 27,
      "b12": 0.88,
      "fat": 33.82,
      "carbs": 2.13,
      "cal": 410,
      "calcium": 711,
      "potassium": 76,
      "zinc": 3.74
    }
  },
  "mozzarella": {
    "fdcId": 170847,
    "desc": "Cheese, mozzarella, part skim milk",
    "per100g": {
      "cal": 254,
      "vitD": 0.3,
      "calcium": 782,
      "fat": 15.92,
      "protein": 24.26,
      "sodium": 619,
      "potassium": 84,
      "zinc": 2.76,
      "carbs": 2.77,
      "fiber": 0,
      "iron": 0.22,
      "magnesium": 23,
      "vitC": 0,
      "folate": 9,
      "b12": 0.82
    }
  },
  "parmesan": {
    "fdcId": 171247,
    "desc": "Cheese, parmesan, grated",
    "per100g": {
      "vitD": 0.5,
      "fat": 27.84,
      "carbs": 13.91,
      "cal": 420,
      "calcium": 853,
      "potassium": 180,
      "zinc": 4.2,
      "protein": 28.42,
      "iron": 0.49,
      "magnesium": 34,
      "sodium": 1804,
      "folate": 6,
      "b12": 1.4,
      "fiber": 0,
      "vitC": 0
    }
  },
  "goat cheese": {
    "fdcId": 173435,
    "desc": "Cheese, goat, soft type",
    "per100g": {
      "vitD": 0.4,
      "cal": 264,
      "sodium": 459,
      "carbs": 0,
      "fat": 21.08,
      "calcium": 140,
      "potassium": 26,
      "zinc": 0.92,
      "vitC": 0,
      "folate": 12,
      "b12": 0.19,
      "fiber": 0,
      "iron": 1.9,
      "magnesium": 16,
      "protein": 18.52
    }
  },
  "halloumi": {
    "fdcId": 170845,
    "desc": "Cheese, mozzarella, whole milk",
    "per100g": {
      "vitC": 0,
      "folate": 7,
      "vitD": 0.4,
      "b12": 2.28,
      "iron": 0.44,
      "magnesium": 20,
      "protein": 22.17,
      "calcium": 505,
      "potassium": 76,
      "zinc": 2.92,
      "sodium": 486,
      "fat": 22.14,
      "carbs": 2.4,
      "cal": 299,
      "fiber": 0
    }
  },
  "ricotta": {
    "fdcId": 171248,
    "desc": "Cheese, ricotta, part skim milk",
    "per100g": {
      "vitD": 0.1,
      "sodium": 99,
      "fiber": 0,
      "iron": 0.44,
      "magnesium": 15,
      "protein": 11.39,
      "vitC": 0,
      "folate": 13,
      "b12": 0.29,
      "fat": 7.91,
      "carbs": 5.14,
      "cal": 138,
      "calcium": 272,
      "potassium": 125,
      "zinc": 1.34
    }
  },
  "cream cheese": {
    "fdcId": 173418,
    "desc": "Cheese, cream",
    "per100g": {
      "folate": 9,
      "b12": 0.22,
      "iron": 0.11,
      "vitD": 0,
      "protein": 6.15,
      "fat": 34.44,
      "carbs": 5.52,
      "cal": 350,
      "calcium": 97,
      "potassium": 132,
      "zinc": 0.5,
      "vitC": 0,
      "magnesium": 9,
      "sodium": 314,
      "fiber": 0
    }
  },
  "light cream cheese": {
    "fdcId": 172207,
    "desc": "Cheese, cream, fat free",
    "per100g": {
      "fiber": 0,
      "protein": 15.69,
      "vitC": 0,
      "folate": 35,
      "b12": 0.95,
      "iron": 0.19,
      "magnesium": 22,
      "sodium": 702,
      "fat": 1,
      "carbs": 7.66,
      "cal": 105,
      "calcium": 351,
      "potassium": 278,
      "zinc": 1.5,
      "vitD": 0
    }
  },
  "protein powder": {
    "fdcId": 173180,
    "desc": "Beverages, Protein powder whey based",
    "per100g": {
      "protein": 78.13,
      "fiber": 3.1,
      "iron": 1.13,
      "magnesium": 195,
      "sodium": 156,
      "vitD": 0,
      "vitC": 0,
      "folate": 33,
      "b12": 2.45,
      "fat": 1.56,
      "carbs": 6.25,
      "cal": 352,
      "calcium": 469,
      "potassium": 500,
      "zinc": 6.18
    }
  },
  "spinach": {
    "fdcId": 168462,
    "desc": "Spinach, raw",
    "per100g": {
      "calcium": 99,
      "potassium": 558,
      "zinc": 0.53,
      "protein": 2.86,
      "iron": 2.71,
      "magnesium": 79,
      "sodium": 79,
      "vitC": 28.1,
      "folate": 194,
      "b12": 0,
      "fiber": 2.2,
      "fat": 0.39,
      "carbs": 3.63,
      "cal": 23,
      "vitD": 0
    }
  },
  "kale": {
    "fdcId": 168421,
    "desc": "Kale, raw",
    "per100g": {
      "b12": 0,
      "protein": 2.92,
      "vitC": 93.4,
      "folate": 62,
      "fiber": 4.1,
      "iron": 1.6,
      "magnesium": 33,
      "sodium": 53,
      "fat": 1.49,
      "carbs": 4.42,
      "cal": 35,
      "calcium": 254,
      "potassium": 348,
      "zinc": 0.39,
      "vitD": 0
    }
  },
  "rocket": {
    "fdcId": 169387,
    "desc": "Arugula, raw",
    "per100g": {
      "carbs": 3.65,
      "fiber": 1.6,
      "protein": 2.58,
      "iron": 1.46,
      "magnesium": 47,
      "sodium": 27,
      "vitC": 15,
      "folate": 97,
      "b12": 0,
      "fat": 0.66,
      "calcium": 160,
      "potassium": 369,
      "zinc": 0.47,
      "vitD": 0,
      "cal": 25
    }
  },
  "romaine": {
    "fdcId": 169247,
    "desc": "Lettuce, cos or romaine, raw",
    "per100g": {
      "carbs": 3.29,
      "cal": 17,
      "sodium": 8,
      "vitC": 4,
      "folate": 136,
      "b12": 0,
      "vitD": 0,
      "fat": 0.3,
      "calcium": 33,
      "potassium": 247,
      "zinc": 0.23,
      "fiber": 2.1,
      "iron": 0.97,
      "magnesium": 14,
      "protein": 1.23
    }
  },
  "lettuce": {
    "fdcId": 169248,
    "desc": "Lettuce, iceberg (includes crisphead types), raw",
    "per100g": {
      "carbs": 2.97,
      "cal": 14,
      "b12": 0,
      "vitC": 2.8,
      "folate": 29,
      "fiber": 1.2,
      "iron": 0.41,
      "magnesium": 7,
      "sodium": 10,
      "protein": 0.9,
      "fat": 0.14,
      "calcium": 18,
      "potassium": 141,
      "zinc": 0.15,
      "vitD": 0
    }
  },
  "mixed greens": {
    "fdcId": 169249,
    "desc": "Lettuce, green leaf, raw",
    "per100g": {
      "vitC": 9.2,
      "fiber": 1.3,
      "carbs": 2.87,
      "b12": 0,
      "cal": 15,
      "vitD": 0,
      "protein": 1.36,
      "iron": 0.86,
      "magnesium": 13,
      "sodium": 28,
      "folate": 38,
      "calcium": 36,
      "potassium": 194,
      "zinc": 0.18,
      "fat": 0.15
    }
  },
  "broccoli": {
    "fdcId": 170379,
    "desc": "Broccoli, raw",
    "per100g": {
      "carbs": 6.64,
      "cal": 34,
      "fat": 0.37,
      "calcium": 47,
      "potassium": 316,
      "zinc": 0.41,
      "protein": 2.82,
      "fiber": 2.6,
      "iron": 0.73,
      "magnesium": 21,
      "sodium": 33,
      "vitC": 89.2,
      "folate": 63,
      "b12": 0,
      "vitD": 0
    }
  },
  "cauliflower": {
    "fdcId": 169986,
    "desc": "Cauliflower, raw",
    "per100g": {
      "carbs": 4.97,
      "cal": 25,
      "folate": 57,
      "b12": 0,
      "vitD": 0,
      "protein": 1.92,
      "fiber": 2,
      "iron": 0.42,
      "magnesium": 15,
      "sodium": 30,
      "vitC": 48.2,
      "fat": 0.28,
      "calcium": 22,
      "potassium": 299,
      "zinc": 0.27
    }
  },
  "cabbage": {
    "fdcId": 169975,
    "desc": "Cabbage, raw",
    "per100g": {
      "fat": 0.1,
      "carbs": 5.8,
      "cal": 25,
      "calcium": 40,
      "potassium": 170,
      "zinc": 0.18,
      "vitC": 36.6,
      "protein": 1.28,
      "fiber": 2.5,
      "iron": 0.47,
      "magnesium": 12,
      "sodium": 18,
      "folate": 43,
      "b12": 0,
      "vitD": 0
    }
  },
  "bok choy": {
    "fdcId": 170390,
    "desc": "Cabbage, chinese (pak-choi), raw",
    "per100g": {
      "fiber": 1,
      "iron": 0.8,
      "magnesium": 19,
      "sodium": 65,
      "protein": 1.5,
      "vitC": 45,
      "folate": 66,
      "b12": 0,
      "fat": 0.2,
      "calcium": 105,
      "potassium": 252,
      "zinc": 0.19,
      "vitD": 0,
      "carbs": 2.18,
      "cal": 13
    }
  },
  "pak choi": {
    "fdcId": 170390,
    "desc": "Cabbage, chinese (pak-choi), raw",
    "per100g": {
      "fiber": 1,
      "iron": 0.8,
      "magnesium": 19,
      "sodium": 65,
      "protein": 1.5,
      "vitC": 45,
      "folate": 66,
      "b12": 0,
      "fat": 0.2,
      "calcium": 105,
      "potassium": 252,
      "zinc": 0.19,
      "vitD": 0,
      "carbs": 2.18,
      "cal": 13
    }
  },
  "brussels sprouts": {
    "fdcId": 170383,
    "desc": "Brussels sprouts, raw",
    "per100g": {
      "fiber": 3.8,
      "carbs": 8.95,
      "cal": 43,
      "protein": 3.38,
      "iron": 1.4,
      "magnesium": 23,
      "sodium": 25,
      "vitC": 85,
      "folate": 61,
      "b12": 0,
      "fat": 0.3,
      "calcium": 42,
      "potassium": 389,
      "zinc": 0.42,
      "vitD": 0
    }
  },
  "asparagus": {
    "fdcId": 168389,
    "desc": "Asparagus, raw",
    "per100g": {
      "vitC": 5.6,
      "folate": 52,
      "protein": 2.2,
      "sodium": 2,
      "b12": 0,
      "carbs": 3.88,
      "cal": 20,
      "vitD": 0,
      "fiber": 2.1,
      "iron": 2.14,
      "magnesium": 14,
      "fat": 0.12,
      "calcium": 24,
      "potassium": 202,
      "zinc": 0.54
    }
  },
  "green beans": {
    "fdcId": 169961,
    "desc": "Beans, snap, green, raw",
    "per100g": {
      "fat": 0.22,
      "calcium": 37,
      "potassium": 211,
      "zinc": 0.24,
      "vitC": 12.2,
      "folate": 33,
      "protein": 1.83,
      "fiber": 2.7,
      "iron": 1.03,
      "magnesium": 25,
      "sodium": 6,
      "carbs": 6.97,
      "cal": 31,
      "b12": 0,
      "vitD": 0
    }
  },
  "carrot": {
    "fdcId": 170393,
    "desc": "Carrots, raw",
    "per100g": {
      "iron": 0.3,
      "magnesium": 12,
      "sodium": 69,
      "vitC": 5.9,
      "folate": 19,
      "protein": 0.93,
      "fat": 0.24,
      "calcium": 33,
      "potassium": 320,
      "zinc": 0.24,
      "b12": 0,
      "carbs": 9.58,
      "cal": 41,
      "fiber": 2.8,
      "vitD": 0
    }
  },
  "zucchini": {
    "fdcId": 169291,
    "desc": "Squash, summer, zucchini, includes skin, raw",
    "per100g": {
      "calcium": 16,
      "potassium": 261,
      "zinc": 0.32,
      "fat": 0.32,
      "carbs": 3.11,
      "cal": 17,
      "fiber": 1,
      "iron": 0.37,
      "magnesium": 18,
      "sodium": 8,
      "protein": 1.21,
      "vitC": 17.9,
      "folate": 24,
      "b12": 0,
      "vitD": 0
    }
  },
  "eggplant": {
    "fdcId": 169228,
    "desc": "Eggplant, raw",
    "per100g": {
      "vitC": 2.2,
      "folate": 22,
      "b12": 0,
      "calcium": 9,
      "potassium": 229,
      "zinc": 0.16,
      "fat": 0.18,
      "carbs": 5.88,
      "cal": 25,
      "fiber": 3,
      "iron": 0.23,
      "magnesium": 14,
      "sodium": 2,
      "protein": 0.98,
      "vitD": 0
    }
  },
  "mushrooms": {
    "fdcId": 169251,
    "desc": "Mushrooms, white, raw",
    "per100g": {
      "b12": 0.04,
      "fiber": 1,
      "fat": 0.34,
      "calcium": 3,
      "potassium": 318,
      "zinc": 0.52,
      "vitC": 2.1,
      "iron": 0.5,
      "magnesium": 9,
      "sodium": 5,
      "protein": 3.09,
      "folate": 17,
      "vitD": 0.2,
      "carbs": 3.26,
      "cal": 22
    }
  },
  "portobello mushrooms": {
    "fdcId": 169255,
    "desc": "Mushrooms, portabella, raw",
    "per100g": {
      "folate": 28,
      "vitC": 0,
      "protein": 2.11,
      "fiber": 1.3,
      "iron": 0.31,
      "sodium": 9,
      "b12": 0.05,
      "calcium": 3,
      "potassium": 364,
      "zinc": 0.53,
      "fat": 0.35,
      "vitD": 0.3,
      "carbs": 3.87,
      "cal": 22
    }
  },
  "bell pepper": {
    "fdcId": 170108,
    "desc": "Peppers, sweet, red, raw",
    "per100g": {
      "fiber": 2.1,
      "folate": 46,
      "cal": 26,
      "vitC": 127.7,
      "sodium": 4,
      "carbs": 6.03,
      "iron": 0.43,
      "magnesium": 12,
      "protein": 0.99,
      "b12": 0,
      "calcium": 7,
      "potassium": 211,
      "zinc": 0.25,
      "fat": 0.3,
      "vitD": 0
    }
  },
  "bell peppers": {
    "fdcId": 170108,
    "desc": "Peppers, sweet, red, raw",
    "per100g": {
      "fiber": 2.1,
      "folate": 46,
      "cal": 26,
      "vitC": 127.7,
      "sodium": 4,
      "carbs": 6.03,
      "iron": 0.43,
      "magnesium": 12,
      "protein": 0.99,
      "b12": 0,
      "calcium": 7,
      "potassium": 211,
      "zinc": 0.25,
      "fat": 0.3,
      "vitD": 0
    }
  },
  "roasted peppers": {
    "fdcId": 170108,
    "desc": "Peppers, sweet, red, raw",
    "per100g": {
      "fiber": 2.1,
      "folate": 46,
      "cal": 26,
      "vitC": 127.7,
      "sodium": 4,
      "carbs": 6.03,
      "iron": 0.43,
      "magnesium": 12,
      "protein": 0.99,
      "b12": 0,
      "calcium": 7,
      "potassium": 211,
      "zinc": 0.25,
      "fat": 0.3,
      "vitD": 0
    }
  },
  "cucumber": {
    "fdcId": 168409,
    "desc": "Cucumber, with peel, raw",
    "per100g": {
      "carbs": 3.63,
      "cal": 15,
      "sodium": 2,
      "b12": 0,
      "calcium": 16,
      "potassium": 147,
      "zinc": 0.2,
      "fat": 0.11,
      "vitC": 2.8,
      "folate": 7,
      "fiber": 0.5,
      "iron": 0.28,
      "magnesium": 13,
      "protein": 0.65,
      "vitD": 0
    }
  },
  "tomatoes": {
    "fdcId": 170457,
    "desc": "Tomatoes, red, ripe, raw, year round average",
    "per100g": {
      "vitC": 13.7,
      "b12": 0,
      "carbs": 3.89,
      "cal": 18,
      "calcium": 10,
      "potassium": 237,
      "zinc": 0.17,
      "fat": 0.2,
      "fiber": 1.2,
      "iron": 0.27,
      "magnesium": 11,
      "sodium": 5,
      "protein": 0.88,
      "folate": 15,
      "vitD": 0
    }
  },
  "cherry tomatoes": {
    "fdcId": 170457,
    "desc": "Tomatoes, red, ripe, raw, year round average",
    "per100g": {
      "vitC": 13.7,
      "b12": 0,
      "carbs": 3.89,
      "cal": 18,
      "calcium": 10,
      "potassium": 237,
      "zinc": 0.17,
      "fat": 0.2,
      "fiber": 1.2,
      "iron": 0.27,
      "magnesium": 11,
      "sodium": 5,
      "protein": 0.88,
      "folate": 15,
      "vitD": 0
    }
  },
  "chopped tomatoes": {
    "fdcId": 170051,
    "desc": "Tomatoes, red, ripe, canned, packed in tomato juice",
    "per100g": {
      "folate": 8,
      "sodium": 115,
      "b12": 0,
      "calcium": 33,
      "fat": 0.25,
      "carbs": 3.47,
      "cal": 16,
      "potassium": 191,
      "zinc": 0.12,
      "vitC": 12.6,
      "fiber": 1.9,
      "iron": 0.57,
      "magnesium": 10,
      "protein": 0.79,
      "vitD": 0
    }
  },
  "onion": {
    "fdcId": 170000,
    "desc": "Onions, raw",
    "per100g": {
      "calcium": 23,
      "potassium": 146,
      "zinc": 0.17,
      "fat": 0.1,
      "carbs": 9.34,
      "cal": 40,
      "vitC": 7.4,
      "folate": 19,
      "protein": 1.1,
      "fiber": 1.7,
      "iron": 0.21,
      "magnesium": 10,
      "sodium": 4,
      "b12": 0,
      "vitD": 0
    }
  },
  "red onion": {
    "fdcId": 170000,
    "desc": "Onions, raw",
    "per100g": {
      "calcium": 23,
      "potassium": 146,
      "zinc": 0.17,
      "fat": 0.1,
      "carbs": 9.34,
      "cal": 40,
      "vitC": 7.4,
      "folate": 19,
      "protein": 1.1,
      "fiber": 1.7,
      "iron": 0.21,
      "magnesium": 10,
      "sodium": 4,
      "b12": 0,
      "vitD": 0
    }
  },
  "garlic": {
    "fdcId": 169230,
    "desc": "Garlic, raw",
    "per100g": {
      "carbs": 33.06,
      "cal": 149,
      "vitC": 31.2,
      "folate": 3,
      "b12": 0,
      "fiber": 2.1,
      "iron": 1.7,
      "magnesium": 25,
      "sodium": 17,
      "protein": 6.36,
      "calcium": 181,
      "potassium": 401,
      "zinc": 1.16,
      "fat": 0.5,
      "vitD": 0
    }
  },
  "sweet potato": {
    "fdcId": 168482,
    "desc": "Sweet potato, raw, unprepared (Includes foods for USDA's Food Distribution Program)",
    "per100g": {
      "fiber": 3,
      "carbs": 20.12,
      "cal": 86,
      "vitC": 2.4,
      "sodium": 55,
      "folate": 11,
      "b12": 0,
      "fat": 0.05,
      "calcium": 30,
      "potassium": 337,
      "zinc": 0.3,
      "iron": 0.61,
      "magnesium": 25,
      "protein": 1.57,
      "vitD": 0
    }
  },
  "baby potatoes": {
    "fdcId": 170026,
    "desc": "Potatoes, flesh and skin, raw",
    "per100g": {
      "fat": 0.09,
      "calcium": 12,
      "magnesium": 23,
      "b12": 0,
      "cal": 77,
      "vitC": 19.7,
      "sodium": 6,
      "folate": 15,
      "protein": 2.05,
      "fiber": 2.1,
      "iron": 0.81,
      "carbs": 17.49,
      "potassium": 425,
      "zinc": 0.3,
      "vitD": 0
    }
  },
  "beetroot": {
    "fdcId": 169146,
    "desc": "Beets, cooked, boiled, drained",
    "per100g": {
      "protein": 1.68,
      "iron": 0.79,
      "magnesium": 23,
      "sodium": 77,
      "vitC": 3.6,
      "folate": 80,
      "b12": 0,
      "fat": 0.18,
      "carbs": 9.96,
      "calcium": 16,
      "potassium": 305,
      "zinc": 0.35,
      "cal": 44,
      "fiber": 2,
      "vitD": 0
    }
  },
  "cooked beetroot": {
    "fdcId": 169146,
    "desc": "Beets, cooked, boiled, drained",
    "per100g": {
      "protein": 1.68,
      "iron": 0.79,
      "magnesium": 23,
      "sodium": 77,
      "vitC": 3.6,
      "folate": 80,
      "b12": 0,
      "fat": 0.18,
      "carbs": 9.96,
      "calcium": 16,
      "potassium": 305,
      "zinc": 0.35,
      "cal": 44,
      "fiber": 2,
      "vitD": 0
    }
  },
  "kimchi": {
    "fdcId": 170392,
    "desc": "Cabbage, kimchi",
    "per100g": {
      "fat": 0.5,
      "carbs": 2.4,
      "cal": 15,
      "calcium": 33,
      "potassium": 151,
      "zinc": 0.22,
      "protein": 1.1,
      "fiber": 1.6,
      "iron": 2.5,
      "magnesium": 14,
      "sodium": 498,
      "vitD": 0,
      "vitC": 0,
      "folate": 52,
      "b12": 0
    }
  },
  "olives": {
    "fdcId": 169094,
    "desc": "Olives, ripe, canned (small-extra large)",
    "per100g": {
      "sodium": 735,
      "calcium": 88,
      "potassium": 8,
      "zinc": 0.22,
      "protein": 0.84,
      "magnesium": 4,
      "vitC": 0.9,
      "folate": 0,
      "b12": 0,
      "fiber": 1.6,
      "iron": 6.28,
      "fat": 10.9,
      "carbs": 6.04,
      "cal": 116,
      "vitD": 0
    }
  },
  "mixed veg": {
    "fdcId": 170471,
    "desc": "Vegetables, mixed, frozen, unprepared",
    "per100g": {
      "fiber": 4,
      "carbs": 13.47,
      "cal": 72,
      "fat": 0.52,
      "calcium": 25,
      "potassium": 212,
      "zinc": 0.45,
      "protein": 3.33,
      "vitC": 10.4,
      "folate": 29,
      "b12": 0,
      "iron": 0.95,
      "magnesium": 24,
      "sodium": 47,
      "vitD": 0
    }
  },
  "mixed stir-fry veg": {
    "fdcId": 170471,
    "desc": "Vegetables, mixed, frozen, unprepared",
    "per100g": {
      "fiber": 4,
      "carbs": 13.47,
      "cal": 72,
      "fat": 0.52,
      "calcium": 25,
      "potassium": 212,
      "zinc": 0.45,
      "protein": 3.33,
      "vitC": 10.4,
      "folate": 29,
      "b12": 0,
      "iron": 0.95,
      "magnesium": 24,
      "sodium": 47,
      "vitD": 0
    }
  },
  "roasted vegetables": {
    "fdcId": 170471,
    "desc": "Vegetables, mixed, frozen, unprepared",
    "per100g": {
      "fiber": 4,
      "carbs": 13.47,
      "cal": 72,
      "fat": 0.52,
      "calcium": 25,
      "potassium": 212,
      "zinc": 0.45,
      "protein": 3.33,
      "vitC": 10.4,
      "folate": 29,
      "b12": 0,
      "iron": 0.95,
      "magnesium": 24,
      "sodium": 47,
      "vitD": 0
    }
  },
  "parsley": {
    "fdcId": 170416,
    "desc": "Parsley, fresh",
    "per100g": {
      "carbs": 6.33,
      "cal": 36,
      "calcium": 138,
      "potassium": 554,
      "zinc": 1.07,
      "fat": 0.79,
      "protein": 2.97,
      "fiber": 3.3,
      "iron": 6.2,
      "magnesium": 50,
      "sodium": 56,
      "vitC": 133,
      "folate": 152,
      "b12": 0,
      "vitD": 0
    }
  },
  "chives": {
    "fdcId": 169994,
    "desc": "Chives, raw",
    "per100g": {
      "cal": 30,
      "protein": 3.27,
      "fiber": 2.5,
      "iron": 1.6,
      "magnesium": 42,
      "sodium": 3,
      "vitC": 58.1,
      "folate": 105,
      "b12": 0,
      "fat": 0.73,
      "calcium": 92,
      "potassium": 296,
      "zinc": 0.56,
      "vitD": 0,
      "carbs": 4.35
    }
  },
  "avocado": {
    "fdcId": 171705,
    "desc": "Avocados, raw, all commercial varieties",
    "per100g": {
      "vitC": 10,
      "protein": 2,
      "fiber": 6.7,
      "iron": 0.55,
      "magnesium": 29,
      "sodium": 7,
      "fat": 14.66,
      "calcium": 12,
      "potassium": 485,
      "zinc": 0.64,
      "folate": 81,
      "b12": 0,
      "carbs": 8.53,
      "cal": 160,
      "vitD": 0
    }
  },
  "banana": {
    "fdcId": 173944,
    "desc": "Bananas, raw",
    "per100g": {
      "carbs": 22.84,
      "cal": 89,
      "b12": 0,
      "vitD": 0,
      "vitC": 8.7,
      "folate": 20,
      "fiber": 2.6,
      "iron": 0.26,
      "magnesium": 27,
      "sodium": 1,
      "protein": 1.09,
      "calcium": 5,
      "potassium": 358,
      "zinc": 0.15,
      "fat": 0.33
    }
  },
  "apple": {
    "fdcId": 171688,
    "desc": "Apples, raw, with skin (Includes foods for USDA's Food Distribution Program)",
    "per100g": {
      "folate": 3,
      "carbs": 13.81,
      "cal": 52,
      "fat": 0.17,
      "calcium": 6,
      "potassium": 107,
      "zinc": 0.04,
      "fiber": 2.4,
      "iron": 0.12,
      "magnesium": 5,
      "sodium": 1,
      "protein": 0.26,
      "b12": 0,
      "vitC": 4.6,
      "vitD": 0
    }
  },
  "mango": {
    "fdcId": 169910,
    "desc": "Mangos, raw",
    "per100g": {
      "fat": 0.38,
      "calcium": 11,
      "potassium": 168,
      "zinc": 0.09,
      "protein": 0.82,
      "vitC": 36.4,
      "fiber": 1.6,
      "iron": 0.16,
      "magnesium": 10,
      "sodium": 1,
      "folate": 43,
      "b12": 0,
      "carbs": 14.98,
      "cal": 60,
      "vitD": 0
    }
  },
  "lemon": {
    "fdcId": 167746,
    "desc": "Lemons, raw, without peel",
    "per100g": {
      "protein": 1.1,
      "vitC": 53,
      "folate": 11,
      "b12": 0,
      "fiber": 2.8,
      "iron": 0.6,
      "magnesium": 8,
      "sodium": 2,
      "fat": 0.3,
      "carbs": 9.32,
      "cal": 29,
      "calcium": 26,
      "potassium": 138,
      "zinc": 0.06,
      "vitD": 0
    }
  },
  "lime": {
    "fdcId": 168155,
    "desc": "Limes, raw",
    "per100g": {
      "fat": 0.2,
      "carbs": 10.54,
      "calcium": 33,
      "potassium": 102,
      "zinc": 0.11,
      "protein": 0.7,
      "iron": 0.6,
      "magnesium": 6,
      "sodium": 2,
      "vitC": 29.1,
      "folate": 8,
      "fiber": 2.8,
      "b12": 0,
      "vitD": 0,
      "cal": 30
    }
  },
  "blueberries": {
    "fdcId": 171711,
    "desc": "Blueberries, raw",
    "per100g": {
      "potassium": 77,
      "sodium": 1,
      "vitC": 9.7,
      "carbs": 14.49,
      "cal": 57,
      "b12": 0,
      "zinc": 0.16,
      "calcium": 6,
      "fat": 0.33,
      "folate": 6,
      "fiber": 2.4,
      "iron": 0.28,
      "magnesium": 6,
      "protein": 0.74,
      "vitD": 0
    }
  },
  "raspberries": {
    "fdcId": 167755,
    "desc": "Raspberries, raw",
    "per100g": {
      "carbs": 11.94,
      "cal": 52,
      "potassium": 151,
      "sodium": 1,
      "vitC": 26.2,
      "b12": 0,
      "vitD": 0,
      "fat": 0.65,
      "calcium": 25,
      "zinc": 0.42,
      "folate": 21,
      "fiber": 6.5,
      "iron": 0.69,
      "magnesium": 22,
      "protein": 1.2
    }
  },
  "berries": {
    "fdcId": 171711,
    "desc": "Blueberries, raw",
    "per100g": {
      "potassium": 77,
      "sodium": 1,
      "vitC": 9.7,
      "carbs": 14.49,
      "cal": 57,
      "b12": 0,
      "zinc": 0.16,
      "calcium": 6,
      "fat": 0.33,
      "folate": 6,
      "fiber": 2.4,
      "iron": 0.28,
      "magnesium": 6,
      "protein": 0.74,
      "vitD": 0
    }
  },
  "mixed berries": {
    "fdcId": 171711,
    "desc": "Blueberries, raw",
    "per100g": {
      "potassium": 77,
      "sodium": 1,
      "vitC": 9.7,
      "carbs": 14.49,
      "cal": 57,
      "b12": 0,
      "zinc": 0.16,
      "calcium": 6,
      "fat": 0.33,
      "folate": 6,
      "fiber": 2.4,
      "iron": 0.28,
      "magnesium": 6,
      "protein": 0.74,
      "vitD": 0
    }
  },
  "frozen berries": {
    "fdcId": 173950,
    "desc": "Blueberries, frozen, unsweetened (Includes foods for USDA's Food Distribution Program)",
    "per100g": {
      "fat": 0.64,
      "carbs": 12.17,
      "cal": 51,
      "calcium": 8,
      "potassium": 54,
      "zinc": 0.07,
      "protein": 0.42,
      "fiber": 2.7,
      "iron": 0.18,
      "magnesium": 5,
      "sodium": 1,
      "vitC": 2.5,
      "folate": 7,
      "b12": 0,
      "vitD": 0
    }
  },
  "olive oil": {
    "fdcId": 171413,
    "desc": "Oil, olive, salad or cooking",
    "per100g": {
      "fat": 100,
      "carbs": 0,
      "cal": 884,
      "calcium": 1,
      "potassium": 1,
      "zinc": 0,
      "iron": 0.56,
      "magnesium": 0,
      "sodium": 2,
      "protein": 0,
      "fiber": 0,
      "vitC": 0,
      "folate": 0,
      "b12": 0,
      "vitD": 0
    }
  },
  "sesame oil": {
    "fdcId": 171016,
    "desc": "Oil, sesame, salad or cooking",
    "per100g": {
      "protein": 0,
      "fiber": 0,
      "iron": 0,
      "magnesium": 0,
      "sodium": 0,
      "b12": 0,
      "vitC": 0,
      "fat": 100,
      "carbs": 0,
      "cal": 884,
      "calcium": 0,
      "potassium": 0,
      "zinc": 0,
      "folate": 0,
      "vitD": 0
    }
  },
  "peanut butter": {
    "fdcId": 172470,
    "desc": "Peanut butter, smooth style, without salt",
    "per100g": {
      "sodium": 17,
      "b12": 0,
      "vitC": 0,
      "folate": 87,
      "protein": 22.21,
      "fiber": 5,
      "iron": 1.74,
      "magnesium": 168,
      "calcium": 49,
      "potassium": 558,
      "zinc": 2.51,
      "fat": 51.36,
      "carbs": 22.31,
      "cal": 598,
      "vitD": 0
    }
  },
  "almond butter": {
    "fdcId": 168588,
    "desc": "Nuts, almond butter, plain, without salt added",
    "per100g": {
      "calcium": 347,
      "potassium": 748,
      "zinc": 3.29,
      "fat": 55.5,
      "fiber": 10.3,
      "iron": 3.49,
      "magnesium": 279,
      "vitC": 0,
      "protein": 20.96,
      "vitD": 0,
      "sodium": 7,
      "carbs": 18.82,
      "cal": 614,
      "folate": 53,
      "b12": 0
    }
  },
  "tahini": {
    "fdcId": 170189,
    "desc": "Seeds, sesame butter, tahini, from roasted and toasted kernels (most common type)",
    "per100g": {
      "vitD": 0,
      "fat": 53.76,
      "carbs": 21.19,
      "cal": 595,
      "calcium": 426,
      "potassium": 414,
      "zinc": 4.62,
      "protein": 17,
      "vitC": 0,
      "folate": 98,
      "b12": 0,
      "fiber": 9.3,
      "iron": 8.95,
      "magnesium": 95,
      "sodium": 115
    }
  },
  "almonds": {
    "fdcId": 170567,
    "desc": "Nuts, almonds",
    "per100g": {
      "vitD": 0,
      "protein": 21.15,
      "fiber": 12.5,
      "iron": 3.71,
      "magnesium": 270,
      "folate": 44,
      "fat": 49.93,
      "carbs": 21.55,
      "cal": 579,
      "calcium": 269,
      "potassium": 733,
      "zinc": 3.12,
      "vitC": 0,
      "sodium": 1,
      "b12": 0
    }
  },
  "walnuts": {
    "fdcId": 170187,
    "desc": "Nuts, walnuts, english",
    "per100g": {
      "calcium": 98,
      "carbs": 13.71,
      "cal": 654,
      "vitD": 0,
      "b12": 0,
      "protein": 15.23,
      "fiber": 6.7,
      "iron": 2.91,
      "magnesium": 158,
      "sodium": 2,
      "vitC": 1.3,
      "folate": 98,
      "potassium": 441,
      "zinc": 3.09,
      "fat": 65.21
    }
  },
  "pecans": {
    "fdcId": 170182,
    "desc": "Nuts, pecans",
    "per100g": {
      "fat": 71.97,
      "calcium": 70,
      "potassium": 410,
      "zinc": 4.53,
      "protein": 9.17,
      "fiber": 9.6,
      "iron": 2.53,
      "magnesium": 121,
      "sodium": 0,
      "vitC": 1.1,
      "folate": 22,
      "carbs": 13.86,
      "cal": 691,
      "vitD": 0,
      "b12": 0
    }
  },
  "peanuts": {
    "fdcId": 172430,
    "desc": "Peanuts, all types, raw",
    "per100g": {
      "fiber": 8.5,
      "b12": 0,
      "sodium": 18,
      "vitC": 0,
      "folate": 240,
      "iron": 4.58,
      "magnesium": 168,
      "protein": 25.8,
      "calcium": 92,
      "potassium": 705,
      "zinc": 3.27,
      "fat": 49.24,
      "carbs": 16.13,
      "cal": 567,
      "vitD": 0
    }
  },
  "chia seeds": {
    "fdcId": 170554,
    "desc": "Seeds, chia seeds, dried",
    "per100g": {
      "protein": 16.54,
      "fiber": 34.4,
      "iron": 7.72,
      "magnesium": 335,
      "sodium": 16,
      "vitC": 1.6,
      "folate": 49,
      "fat": 30.74,
      "carbs": 42.12,
      "cal": 486,
      "potassium": 407,
      "zinc": 4.58,
      "calcium": 631,
      "b12": 0
    }
  },
  "sesame seeds": {
    "fdcId": 170150,
    "desc": "Seeds, sesame seeds, whole, dried",
    "per100g": {
      "vitD": 0,
      "protein": 17.73,
      "fiber": 11.8,
      "iron": 14.55,
      "magnesium": 351,
      "sodium": 11,
      "vitC": 0,
      "folate": 97,
      "b12": 0,
      "fat": 49.67,
      "carbs": 23.45,
      "cal": 573,
      "calcium": 975,
      "potassium": 468,
      "zinc": 7.75
    }
  },
  "pumpkin seeds": {
    "fdcId": 170556,
    "desc": "Seeds, pumpkin and squash seed kernels, dried",
    "per100g": {
      "vitD": 0,
      "carbs": 10.71,
      "cal": 559,
      "vitC": 1.9,
      "folate": 58,
      "b12": 0,
      "protein": 30.23,
      "fiber": 6,
      "iron": 8.82,
      "magnesium": 592,
      "sodium": 7,
      "calcium": 46,
      "potassium": 809,
      "zinc": 7.81,
      "fat": 49.05
    }
  },
  "sourdough bread": {
    "fdcId": 172686,
    "desc": "Bread, wheat",
    "per100g": {
      "iron": 3.6,
      "magnesium": 41,
      "sodium": 473,
      "protein": 10.67,
      "fat": 4.53,
      "carbs": 47.54,
      "cal": 274,
      "calcium": 125,
      "potassium": 141,
      "zinc": 1.04,
      "fiber": 4,
      "folate": 85,
      "b12": 0,
      "vitC": 0.2,
      "vitD": 0
    }
  },
  "whole-grain bread": {
    "fdcId": 172688,
    "desc": "Bread, whole-wheat, commercially prepared",
    "per100g": {
      "fat": 3.5,
      "carbs": 42.71,
      "cal": 252,
      "calcium": 161,
      "potassium": 254,
      "zinc": 1.77,
      "protein": 12.45,
      "fiber": 6,
      "iron": 2.47,
      "magnesium": 75,
      "sodium": 455,
      "folate": 42,
      "vitD": 0,
      "b12": 0,
      "vitC": 0
    }
  },
  "whole-grain toast": {
    "fdcId": 172689,
    "desc": "Bread, whole-wheat, commercially prepared, toasted",
    "per100g": {
      "sodium": 565,
      "vitC": 0,
      "fiber": 7.5,
      "iron": 2.96,
      "magnesium": 99,
      "protein": 16.27,
      "folate": 52,
      "b12": 0,
      "fat": 4.07,
      "carbs": 51.16,
      "cal": 306,
      "calcium": 130,
      "potassium": 326,
      "zinc": 2.15,
      "vitD": 0
    }
  },
  "rye bread": {
    "fdcId": 172684,
    "desc": "Bread, rye",
    "per100g": {
      "fiber": 5.8,
      "folate": 110,
      "cal": 259,
      "protein": 8.5,
      "iron": 2.83,
      "magnesium": 40,
      "b12": 0,
      "fat": 3.3,
      "carbs": 48.3,
      "calcium": 73,
      "potassium": 166,
      "zinc": 1.14,
      "sodium": 603,
      "vitD": 0,
      "vitC": 0.4
    }
  },
  "wholegrain bagel": {
    "fdcId": 167533,
    "desc": "Bagels, wheat",
    "per100g": {
      "protein": 10.2,
      "fiber": 4.1,
      "iron": 2.76,
      "magnesium": 51,
      "sodium": 439,
      "vitD": 0,
      "vitC": 0,
      "folate": 76,
      "b12": 0,
      "fat": 1.53,
      "carbs": 48.89,
      "cal": 250,
      "calcium": 20,
      "potassium": 165,
      "zinc": 1.1
    }
  },
  "corn tortillas": {
    "fdcId": 175036,
    "desc": "Tortillas, ready-to-bake or -fry, corn",
    "per100g": {
      "protein": 5.7,
      "fiber": 6.3,
      "iron": 1.23,
      "magnesium": 72,
      "sodium": 45,
      "folate": 5,
      "calcium": 81,
      "potassium": 186,
      "zinc": 1.31,
      "fat": 2.85,
      "carbs": 44.64,
      "cal": 218,
      "vitC": 0,
      "b12": 0,
      "vitD": 0
    }
  },
  "tortillas": {
    "fdcId": 175037,
    "desc": "Tortillas, ready-to-bake or -fry, flour, refrigerated",
    "per100g": {
      "fat": 7.99,
      "carbs": 49.38,
      "cal": 306,
      "calcium": 146,
      "potassium": 125,
      "zinc": 0.53,
      "vitC": 0,
      "folate": 94,
      "b12": 0,
      "protein": 8.2,
      "fiber": 3.5,
      "iron": 3.63,
      "magnesium": 22,
      "sodium": 736,
      "vitD": 0
    }
  },
  "whole-wheat tortilla": {
    "fdcId": 174081,
    "desc": "Tortillas, ready-to-bake or -fry, whole wheat",
    "per100g": {
      "fat": 9.76,
      "carbs": 45.89,
      "cal": 310,
      "calcium": 244,
      "potassium": 262,
      "zinc": 1.92,
      "protein": 9.76,
      "fiber": 9.8,
      "iron": 2.63,
      "magnesium": 85,
      "vitD": 0,
      "vitC": 0,
      "folate": 138,
      "b12": 0,
      "sodium": 617
    }
  },
  "whole-wheat wrap": {
    "fdcId": 174081,
    "desc": "Tortillas, ready-to-bake or -fry, whole wheat",
    "per100g": {
      "fat": 9.76,
      "carbs": 45.89,
      "cal": 310,
      "calcium": 244,
      "potassium": 262,
      "zinc": 1.92,
      "protein": 9.76,
      "fiber": 9.8,
      "iron": 2.63,
      "magnesium": 85,
      "vitD": 0,
      "vitC": 0,
      "folate": 138,
      "b12": 0,
      "sodium": 617
    }
  },
  "honey": {
    "fdcId": 169640,
    "desc": "Honey",
    "per100g": {
      "protein": 0.3,
      "fiber": 0.2,
      "iron": 0.42,
      "magnesium": 2,
      "sodium": 4,
      "vitC": 0.5,
      "folate": 2,
      "b12": 0,
      "fat": 0,
      "carbs": 82.4,
      "cal": 304,
      "calcium": 6,
      "potassium": 52,
      "zinc": 0.22,
      "vitD": 0
    }
  },
  "hummus": {
    "fdcId": 174289,
    "desc": "Hummus, commercial",
    "per100g": {
      "vitD": 0,
      "b12": 0,
      "vitC": 0,
      "folate": 48,
      "protein": 7.78,
      "fiber": 5.5,
      "iron": 2.54,
      "magnesium": 75,
      "sodium": 426,
      "fat": 17.82,
      "carbs": 15,
      "cal": 237,
      "calcium": 47,
      "potassium": 312,
      "zinc": 1.44
    }
  },
  "pesto": {
    "fdcId": 171579,
    "desc": "Sauce, pesto, ready-to-serve, refrigerated",
    "per100g": {
      "fat": 37.6,
      "carbs": 10.09,
      "cal": 418,
      "calcium": 306,
      "potassium": 560,
      "zinc": 1.33,
      "protein": 9.83,
      "fiber": 1.8,
      "iron": 0.57,
      "magnesium": 47,
      "sodium": 603,
      "vitC": 0,
      "folate": 16
    }
  },
  "salsa": {
    "fdcId": 174524,
    "desc": "Sauce, salsa, ready-to-serve",
    "per100g": {
      "b12": 0,
      "folate": 4,
      "vitC": 1.9,
      "magnesium": 15,
      "sodium": 711,
      "fiber": 1.9,
      "iron": 0.42,
      "protein": 1.52,
      "carbs": 6.64,
      "potassium": 275,
      "zinc": 0.18,
      "calcium": 30,
      "cal": 29,
      "fat": 0.17,
      "vitD": 0
    }
  },
  "tomato sauce": {
    "fdcId": 169074,
    "desc": "Tomato sauce, canned, no salt added",
    "per100g": {
      "protein": 1.2,
      "cal": 24,
      "vitC": 7,
      "sodium": 11,
      "fiber": 1.5,
      "b12": 0,
      "calcium": 14,
      "potassium": 297,
      "zinc": 0.22,
      "fat": 0.3,
      "carbs": 5.31,
      "iron": 0.96,
      "magnesium": 15,
      "folate": 9,
      "vitD": 0
    }
  },
  "enchilada sauce": {
    "fdcId": 169074,
    "desc": "Tomato sauce, canned, no salt added",
    "per100g": {
      "protein": 1.2,
      "cal": 24,
      "vitC": 7,
      "sodium": 11,
      "fiber": 1.5,
      "b12": 0,
      "calcium": 14,
      "potassium": 297,
      "zinc": 0.22,
      "fat": 0.3,
      "carbs": 5.31,
      "iron": 0.96,
      "magnesium": 15,
      "folate": 9,
      "vitD": 0
    }
  },
  "tikka masala sauce": {
    "fdcId": 169074,
    "desc": "Tomato sauce, canned, no salt added",
    "per100g": {
      "protein": 1.2,
      "cal": 24,
      "vitC": 7,
      "sodium": 11,
      "fiber": 1.5,
      "b12": 0,
      "calcium": 14,
      "potassium": 297,
      "zinc": 0.22,
      "fat": 0.3,
      "carbs": 5.31,
      "iron": 0.96,
      "magnesium": 15,
      "folate": 9,
      "vitD": 0
    }
  },
  "buffalo sauce": {
    "fdcId": 171186,
    "desc": "Sauce, hot chile, sriracha",
    "per100g": {
      "protein": 1.93,
      "fiber": 2.2,
      "iron": 1.64,
      "magnesium": 16,
      "sodium": 2124,
      "vitC": 26.9,
      "folate": 22,
      "fat": 0.93,
      "carbs": 19.16,
      "cal": 93,
      "calcium": 18,
      "potassium": 321,
      "zinc": 0.24
    }
  },
  "sriracha": {
    "fdcId": 171186,
    "desc": "Sauce, hot chile, sriracha",
    "per100g": {
      "protein": 1.93,
      "fiber": 2.2,
      "iron": 1.64,
      "magnesium": 16,
      "sodium": 2124,
      "vitC": 26.9,
      "folate": 22,
      "fat": 0.93,
      "carbs": 19.16,
      "cal": 93,
      "calcium": 18,
      "potassium": 321,
      "zinc": 0.24
    }
  },
  "soy sauce": {
    "fdcId": 174277,
    "desc": "Soy sauce made from soy and wheat (shoyu)",
    "per100g": {
      "fat": 0.57,
      "carbs": 4.93,
      "calcium": 33,
      "potassium": 435,
      "zinc": 0.87,
      "protein": 8.14,
      "iron": 1.45,
      "magnesium": 74,
      "sodium": 5493,
      "cal": 53,
      "vitD": 0,
      "vitC": 0,
      "folate": 14,
      "b12": 0,
      "fiber": 0.8
    }
  },
  "teriyaki sauce": {
    "fdcId": 171167,
    "desc": "Sauce, teriyaki, ready-to-serve",
    "per100g": {
      "calcium": 25,
      "potassium": 225,
      "zinc": 0.1,
      "vitC": 0,
      "protein": 5.93,
      "fiber": 0.1,
      "iron": 1.7,
      "magnesium": 61,
      "sodium": 3833,
      "fat": 0.02,
      "carbs": 15.56,
      "cal": 89,
      "folate": 8,
      "b12": 0,
      "vitD": 0
    }
  },
  "ginger-soy sauce": {
    "fdcId": 171167,
    "desc": "Sauce, teriyaki, ready-to-serve",
    "per100g": {
      "calcium": 25,
      "potassium": 225,
      "zinc": 0.1,
      "vitC": 0,
      "protein": 5.93,
      "fiber": 0.1,
      "iron": 1.7,
      "magnesium": 61,
      "sodium": 3833,
      "fat": 0.02,
      "carbs": 15.56,
      "cal": 89,
      "folate": 8,
      "b12": 0,
      "vitD": 0
    }
  },
  "soy-ginger sauce": {
    "fdcId": 171167,
    "desc": "Sauce, teriyaki, ready-to-serve",
    "per100g": {
      "calcium": 25,
      "potassium": 225,
      "zinc": 0.1,
      "vitC": 0,
      "protein": 5.93,
      "fiber": 0.1,
      "iron": 1.7,
      "magnesium": 61,
      "sodium": 3833,
      "fat": 0.02,
      "carbs": 15.56,
      "cal": 89,
      "folate": 8,
      "b12": 0,
      "vitD": 0
    }
  },
  "sesame-soy sauce": {
    "fdcId": 171167,
    "desc": "Sauce, teriyaki, ready-to-serve",
    "per100g": {
      "calcium": 25,
      "potassium": 225,
      "zinc": 0.1,
      "vitC": 0,
      "protein": 5.93,
      "fiber": 0.1,
      "iron": 1.7,
      "magnesium": 61,
      "sodium": 3833,
      "fat": 0.02,
      "carbs": 15.56,
      "cal": 89,
      "folate": 8,
      "b12": 0,
      "vitD": 0
    }
  },
  "tamarind sauce": {
    "fdcId": 171167,
    "desc": "Sauce, teriyaki, ready-to-serve",
    "per100g": {
      "calcium": 25,
      "potassium": 225,
      "zinc": 0.1,
      "vitC": 0,
      "protein": 5.93,
      "fiber": 0.1,
      "iron": 1.7,
      "magnesium": 61,
      "sodium": 3833,
      "fat": 0.02,
      "carbs": 15.56,
      "cal": 89,
      "folate": 8,
      "b12": 0,
      "vitD": 0
    }
  },
  "miso paste": {
    "fdcId": 172442,
    "desc": "Miso",
    "per100g": {
      "protein": 12.79,
      "carbs": 25.37,
      "cal": 198,
      "vitD": 0,
      "vitC": 0,
      "folate": 19,
      "b12": 0.08,
      "fiber": 5.4,
      "iron": 2.49,
      "magnesium": 48,
      "sodium": 3728,
      "calcium": 57,
      "potassium": 210,
      "zinc": 2.56,
      "fat": 6.01
    }
  },
  "harissa": {
    "fdcId": 171186,
    "desc": "Sauce, hot chile, sriracha",
    "per100g": {
      "protein": 1.93,
      "fiber": 2.2,
      "iron": 1.64,
      "magnesium": 16,
      "sodium": 2124,
      "vitC": 26.9,
      "folate": 22,
      "fat": 0.93,
      "carbs": 19.16,
      "cal": 93,
      "calcium": 18,
      "potassium": 321,
      "zinc": 0.24
    }
  },
  "horseradish": {
    "fdcId": 173472,
    "desc": "Horseradish, prepared",
    "per100g": {
      "protein": 1.18,
      "vitC": 24.9,
      "fat": 0.69,
      "carbs": 11.29,
      "cal": 48,
      "b12": 0,
      "iron": 0.42,
      "magnesium": 27,
      "folate": 57,
      "calcium": 56,
      "potassium": 246,
      "zinc": 0.83,
      "sodium": 420,
      "vitD": 0,
      "fiber": 3.3
    }
  },
  "light caesar dressing": {
    "fdcId": 169877,
    "desc": "Salad dressing, caesar, low calorie",
    "per100g": {
      "calcium": 24,
      "potassium": 29,
      "zinc": 0.11,
      "fat": 4.4,
      "carbs": 18.6,
      "cal": 110,
      "vitC": 0,
      "folate": 2,
      "b12": 0.03,
      "protein": 0.3,
      "fiber": 0.1,
      "iron": 0.18,
      "magnesium": 2,
      "sodium": 1148,
      "vitD": 0
    }
  },
  "curry powder": {
    "fdcId": 170924,
    "desc": "Spices, curry powder",
    "per100g": {
      "cal": 325,
      "sodium": 52,
      "b12": 0,
      "fiber": 53.2,
      "iron": 19.1,
      "magnesium": 255,
      "protein": 14.29,
      "folate": 56,
      "vitC": 0.7,
      "fat": 14.01,
      "carbs": 55.83,
      "calcium": 525,
      "potassium": 1170,
      "zinc": 4.7,
      "vitD": 0
    }
  },
  "cumin": {
    "fdcId": 170923,
    "desc": "Spices, cumin seed",
    "per100g": {
      "protein": 17.81,
      "fiber": 10.5,
      "iron": 66.36,
      "magnesium": 366,
      "sodium": 168,
      "vitC": 7.7,
      "b12": 0,
      "fat": 22.27,
      "carbs": 44.24,
      "cal": 375,
      "calcium": 931,
      "potassium": 1788,
      "zinc": 4.8,
      "folate": 10,
      "vitD": 0
    }
  },
  "turmeric": {
    "fdcId": 172231,
    "desc": "Spices, turmeric, ground",
    "per100g": {
      "b12": 0,
      "fat": 3.25,
      "carbs": 67.14,
      "cal": 312,
      "calcium": 168,
      "potassium": 2080,
      "zinc": 4.5,
      "protein": 9.68,
      "fiber": 22.7,
      "iron": 55,
      "magnesium": 208,
      "sodium": 27,
      "vitC": 0.7,
      "folate": 20,
      "vitD": 0
    }
  },
  "paprika": {
    "fdcId": 171329,
    "desc": "Spices, paprika",
    "per100g": {
      "b12": 0,
      "fiber": 34.9,
      "iron": 21.14,
      "magnesium": 178,
      "sodium": 68,
      "vitC": 0.9,
      "folate": 49,
      "protein": 14.14,
      "calcium": 229,
      "potassium": 2280,
      "zinc": 4.33,
      "fat": 12.89,
      "carbs": 53.99,
      "cal": 282,
      "vitD": 0
    }
  },
  "smoked paprika": {
    "fdcId": 171329,
    "desc": "Spices, paprika",
    "per100g": {
      "b12": 0,
      "fiber": 34.9,
      "iron": 21.14,
      "magnesium": 178,
      "sodium": 68,
      "vitC": 0.9,
      "folate": 49,
      "protein": 14.14,
      "calcium": 229,
      "potassium": 2280,
      "zinc": 4.33,
      "fat": 12.89,
      "carbs": 53.99,
      "cal": 282,
      "vitD": 0
    }
  },
  "chili powder": {
    "fdcId": 171319,
    "desc": "Spices, chili powder",
    "per100g": {
      "b12": 0,
      "sodium": 2867,
      "fat": 14.28,
      "carbs": 49.7,
      "cal": 282,
      "calcium": 330,
      "potassium": 1950,
      "zinc": 4.3,
      "protein": 13.46,
      "fiber": 34.8,
      "iron": 17.3,
      "magnesium": 149,
      "vitC": 0.7,
      "folate": 28,
      "vitD": 0
    }
  },
  "cinnamon": {
    "fdcId": 171320,
    "desc": "Spices, cinnamon, ground",
    "per100g": {
      "b12": 0,
      "folate": 6,
      "iron": 8.32,
      "magnesium": 60,
      "fiber": 53.1,
      "protein": 3.99,
      "vitC": 3.8,
      "sodium": 10,
      "calcium": 1002,
      "fat": 1.24,
      "carbs": 80.59,
      "cal": 247,
      "potassium": 431,
      "zinc": 1.83,
      "vitD": 0
    }
  },
  "cocoa": {
    "fdcId": 169593,
    "desc": "Cocoa, dry powder, unsweetened",
    "per100g": {
      "carbs": 57.9,
      "cal": 228,
      "fiber": 37,
      "iron": 13.86,
      "magnesium": 499,
      "sodium": 21,
      "protein": 19.6,
      "vitC": 0,
      "folate": 32,
      "b12": 0,
      "fat": 13.7,
      "calcium": 128,
      "potassium": 1524,
      "zinc": 6.81,
      "vitD": 0
    }
  },
  "matcha": {
    "fdcId": 171917,
    "desc": "Beverages, tea, green, brewed, regular",
    "per100g": {
      "fat": 0,
      "carbs": 0,
      "cal": 1,
      "calcium": 0,
      "potassium": 8,
      "zinc": 0.01,
      "vitD": 0,
      "protein": 0.22,
      "fiber": 0,
      "iron": 0.02,
      "magnesium": 1,
      "sodium": 1,
      "folate": 0,
      "b12": 0,
      "vitC": 0
    }
  },
  "cajun spice": {
    "fdcId": 171329,
    "desc": "Spices, paprika",
    "per100g": {
      "b12": 0,
      "fiber": 34.9,
      "iron": 21.14,
      "magnesium": 178,
      "sodium": 68,
      "vitC": 0.9,
      "folate": 49,
      "protein": 14.14,
      "calcium": 229,
      "potassium": 2280,
      "zinc": 4.33,
      "fat": 12.89,
      "carbs": 53.99,
      "cal": 282,
      "vitD": 0
    }
  },
  "fajita spice": {
    "fdcId": 171319,
    "desc": "Spices, chili powder",
    "per100g": {
      "b12": 0,
      "sodium": 2867,
      "fat": 14.28,
      "carbs": 49.7,
      "cal": 282,
      "calcium": 330,
      "potassium": 1950,
      "zinc": 4.3,
      "protein": 13.46,
      "fiber": 34.8,
      "iron": 17.3,
      "magnesium": 149,
      "vitC": 0.7,
      "folate": 28,
      "vitD": 0
    }
  },
  "taco spice": {
    "fdcId": 171319,
    "desc": "Spices, chili powder",
    "per100g": {
      "b12": 0,
      "sodium": 2867,
      "fat": 14.28,
      "carbs": 49.7,
      "cal": 282,
      "calcium": 330,
      "potassium": 1950,
      "zinc": 4.3,
      "protein": 13.46,
      "fiber": 34.8,
      "iron": 17.3,
      "magnesium": 149,
      "vitC": 0.7,
      "folate": 28,
      "vitD": 0
    }
  },
  "shawarma spice": {
    "fdcId": 170923,
    "desc": "Spices, cumin seed",
    "per100g": {
      "protein": 17.81,
      "fiber": 10.5,
      "iron": 66.36,
      "magnesium": 366,
      "sodium": 168,
      "vitC": 7.7,
      "b12": 0,
      "fat": 22.27,
      "carbs": 44.24,
      "cal": 375,
      "calcium": 931,
      "potassium": 1788,
      "zinc": 4.8,
      "folate": 10,
      "vitD": 0
    }
  },
  "tikka spice": {
    "fdcId": 170924,
    "desc": "Spices, curry powder",
    "per100g": {
      "cal": 325,
      "sodium": 52,
      "b12": 0,
      "fiber": 53.2,
      "iron": 19.1,
      "magnesium": 255,
      "protein": 14.29,
      "folate": 56,
      "vitC": 0.7,
      "fat": 14.01,
      "carbs": 55.83,
      "calcium": 525,
      "potassium": 1170,
      "zinc": 4.7,
      "vitD": 0
    }
  },
  "ras el hanout": {
    "fdcId": 170924,
    "desc": "Spices, curry powder",
    "per100g": {
      "cal": 325,
      "sodium": 52,
      "b12": 0,
      "fiber": 53.2,
      "iron": 19.1,
      "magnesium": 255,
      "protein": 14.29,
      "folate": 56,
      "vitC": 0.7,
      "fat": 14.01,
      "carbs": 55.83,
      "calcium": 525,
      "potassium": 1170,
      "zinc": 4.7,
      "vitD": 0
    }
  }
};

export const UNIT_GRAMS: { default: Record<string, number>; perIngredient: Record<string, Record<string, number>> } = {
  "default": {
    "g": 1,
    "ml": 1,
    "tbsp": 15,
    "tsp": 5,
    "piece": 100,
    "pieces": 100,
    "can": 240,
    "scoop": 30,
    "slice": 30,
    "slices": 30,
    "clove": 3,
    "cloves": 3,
    "small": 70,
    "large": 150,
    "leaves": 2,
    "count": 100
  },
  "perIngredient": {
    "olive oil": {
      "tbsp": 13.5,
      "tsp": 4.5
    },
    "sesame oil": {
      "tbsp": 13.6,
      "tsp": 4.5
    },
    "peanut butter": {
      "tbsp": 16
    },
    "almond butter": {
      "tbsp": 16
    },
    "tahini": {
      "tbsp": 15
    },
    "honey": {
      "tsp": 7,
      "tbsp": 21
    },
    "soy sauce": {
      "tbsp": 16,
      "tsp": 5.3
    },
    "sriracha": {
      "tsp": 5,
      "tbsp": 15
    },
    "miso paste": {
      "tbsp": 17,
      "tsp": 5.7
    },
    "pesto": {
      "tbsp": 16
    },
    "hummus": {
      "tbsp": 15
    },
    "cocoa": {
      "tsp": 2.5,
      "tbsp": 7.4
    },
    "matcha": {
      "tsp": 2
    },
    "chia seeds": {
      "tbsp": 12,
      "tsp": 4
    },
    "sesame seeds": {
      "tbsp": 9,
      "tsp": 3
    },
    "pumpkin seeds": {
      "tbsp": 9.5
    },
    "cumin": {
      "tsp": 2.1,
      "tbsp": 6.3
    },
    "turmeric": {
      "tsp": 3,
      "tbsp": 9
    },
    "paprika": {
      "tsp": 2.3,
      "tbsp": 6.9
    },
    "smoked paprika": {
      "tsp": 2.3,
      "tbsp": 6.9
    },
    "chili powder": {
      "tsp": 2.7,
      "tbsp": 8
    },
    "curry powder": {
      "tsp": 2,
      "tbsp": 6
    },
    "cinnamon": {
      "tsp": 2.6,
      "tbsp": 7.8
    },
    "cajun spice": {
      "tsp": 2.4,
      "tbsp": 7.2
    },
    "fajita spice": {
      "tsp": 2.4,
      "tbsp": 7.2
    },
    "taco spice": {
      "tsp": 2.4,
      "tbsp": 7.2
    },
    "shawarma spice": {
      "tsp": 2.4,
      "tbsp": 7.2
    },
    "tikka spice": {
      "tsp": 2.4,
      "tbsp": 7.2
    },
    "ras el hanout": {
      "tsp": 2.4,
      "tbsp": 7.2
    },
    "harissa": {
      "tsp": 5,
      "tbsp": 15
    },
    "milk": {
      "ml": 1.03
    },
    "eggs": {
      "count": 50,
      "piece": 50,
      "pieces": 50
    },
    "egg": {
      "count": 50,
      "piece": 50
    },
    "egg whites": {
      "count": 33,
      "piece": 33
    },
    "avocado": {
      "count": 200,
      "piece": 200
    },
    "banana": {
      "count": 118,
      "piece": 118
    },
    "apple": {
      "count": 182,
      "piece": 182
    },
    "mango": {
      "count": 200,
      "piece": 200
    },
    "lemon": {
      "count": 58,
      "piece": 58
    },
    "lime": {
      "count": 67,
      "piece": 67
    },
    "onion": {
      "count": 110,
      "piece": 110,
      "small": 70
    },
    "red onion": {
      "count": 110,
      "piece": 110,
      "small": 70
    },
    "carrot": {
      "count": 61,
      "piece": 61
    },
    "cucumber": {
      "count": 300,
      "piece": 300
    },
    "bell pepper": {
      "count": 119,
      "piece": 119
    },
    "bell peppers": {
      "count": 119,
      "piece": 119
    },
    "zucchini": {
      "count": 196,
      "piece": 196
    },
    "sweet potato": {
      "count": 130,
      "piece": 130
    },
    "baby potatoes": {
      "count": 30,
      "piece": 30
    },
    "eggplant": {
      "count": 450,
      "piece": 450
    },
    "garlic": {
      "clove": 3,
      "cloves": 3,
      "count": 3
    },
    "chicken breast": {
      "count": 174,
      "piece": 174
    },
    "chicken thigh": {
      "count": 90,
      "piece": 90
    },
    "salmon fillet": {
      "count": 150,
      "piece": 150
    },
    "cod fillet": {
      "count": 150,
      "piece": 150
    },
    "portobello mushrooms": {
      "count": 84,
      "piece": 84
    },
    "canned tuna": {
      "can": 120
    },
    "chickpeas": {
      "can": 240
    },
    "black beans": {
      "can": 240
    },
    "kidney beans": {
      "can": 240
    },
    "cannellini beans": {
      "can": 240
    },
    "chopped tomatoes": {
      "can": 400
    },
    "corn": {
      "can": 165
    },
    "lentils": {
      "can": 240
    },
    "protein powder": {
      "scoop": 30
    },
    "corn tortillas": {
      "count": 26,
      "piece": 26,
      "pieces": 26
    },
    "tortillas": {
      "count": 45,
      "piece": 45,
      "pieces": 45
    },
    "whole-wheat tortilla": {
      "count": 45,
      "piece": 45
    },
    "whole-wheat wrap": {
      "count": 45,
      "piece": 45
    },
    "wholegrain bagel": {
      "count": 95,
      "piece": 95
    },
    "sourdough bread": {
      "slice": 36,
      "slices": 36,
      "count": 36
    },
    "whole-grain bread": {
      "slice": 32,
      "slices": 32,
      "count": 32
    },
    "whole-grain toast": {
      "slice": 32,
      "slices": 32,
      "count": 32
    },
    "rye bread": {
      "slice": 32,
      "slices": 32,
      "count": 32
    },
    "lettuce": {
      "leaves": 5,
      "count": 5
    },
    "romaine": {
      "leaves": 6,
      "count": 6
    },
    "chives": {
      "tbsp": 3,
      "tsp": 1
    },
    "parsley": {
      "tbsp": 4,
      "tsp": 1.3
    }
  }
};
