// GENERATED by scripts/build-nutrients.mts from scripts/ingredient-map.json.
// Do not edit by hand — run `npm run build:nutrients -- --emit`.
// Every curated ingredient's PERMANENT id. A recipe references an ingredient by its slug, and the
// union type below makes tsc reject one that does not exist (docs/v1/06-ingredient-identity.md).

export const INGREDIENT_SLUGS = [
  "brown-rice",
  "rice",
  "cooked-rice",
  "quinoa",
  "bulgur",
  "couscous",
  "rolled-oats",
  "oat-flour",
  "muesli",
  "granola",
  "whole-wheat-pasta",
  "whole-wheat-penne",
  "whole-wheat-spaghetti",
  "orzo",
  "egg-noodles",
  "soba-noodles",
  "rice-noodles",
  "panko",
  "chickpea-flour",
  "chicken-breast",
  "chicken-thigh",
  "turkey-breast",
  "ground-turkey",
  "turkey-sausage",
  "lean-beef",
  "lean-steak",
  "beef-strips",
  "lean-ground-beef",
  "lean-roast-beef",
  "pork-tenderloin",
  "lean-pork-sausage",
  "salmon-fillet",
  "smoked-salmon",
  "cod-fillet",
  "canned-tuna",
  "smoked-mackerel",
  "smoked-trout",
  "shrimp",
  "prawns",
  "eggs",
  "egg",
  "egg-whites",
  "firm-tofu",
  "tempeh",
  "edamame",
  "bean-sprouts",
  "chickpeas",
  "black-beans",
  "kidney-beans",
  "cannellini-beans",
  "lentils",
  "green-lentils",
  "red-lentils",
  "peas",
  "corn",
  "greek-yogurt",
  "yogurt",
  "milk",
  "cottage-cheese",
  "feta",
  "cheddar",
  "mozzarella",
  "parmesan",
  "goat-cheese",
  "halloumi",
  "ricotta",
  "cream-cheese",
  "light-cream-cheese",
  "protein-powder",
  "soy-protein-powder",
  "spinach",
  "kale",
  "rocket",
  "romaine",
  "lettuce",
  "mixed-greens",
  "broccoli",
  "cauliflower",
  "cabbage",
  "bok-choy",
  "pak-choi",
  "brussels-sprouts",
  "asparagus",
  "green-beans",
  "carrot",
  "zucchini",
  "eggplant",
  "mushrooms",
  "portobello-mushrooms",
  "bell-pepper",
  "bell-peppers",
  "roasted-peppers",
  "cucumber",
  "tomatoes",
  "cherry-tomatoes",
  "chopped-tomatoes",
  "onion",
  "red-onion",
  "garlic",
  "sweet-potato",
  "baby-potatoes",
  "beetroot",
  "cooked-beetroot",
  "kimchi",
  "olives",
  "mixed-veg",
  "mixed-stir-fry-veg",
  "roasted-vegetables",
  "parsley",
  "chives",
  "avocado",
  "banana",
  "apple",
  "mango",
  "lemon",
  "lime",
  "blueberries",
  "raspberries",
  "berries",
  "mixed-berries",
  "frozen-berries",
  "olive-oil",
  "sesame-oil",
  "peanut-butter",
  "almond-butter",
  "tahini",
  "almonds",
  "walnuts",
  "pecans",
  "peanuts",
  "chia-seeds",
  "sesame-seeds",
  "pumpkin-seeds",
  "sourdough-bread",
  "whole-grain-bread",
  "whole-grain-toast",
  "rye-bread",
  "wholegrain-bagel",
  "corn-tortillas",
  "tortillas",
  "whole-wheat-tortilla",
  "whole-wheat-wrap",
  "honey",
  "hummus",
  "pesto",
  "salsa",
  "tomato-sauce",
  "enchilada-sauce",
  "tikka-masala-sauce",
  "buffalo-sauce",
  "sriracha",
  "soy-sauce",
  "teriyaki-sauce",
  "ginger-soy-sauce",
  "soy-ginger-sauce",
  "sesame-soy-sauce",
  "tamarind-sauce",
  "miso-paste",
  "harissa",
  "horseradish",
  "light-caesar-dressing",
  "curry-powder",
  "cumin",
  "turmeric",
  "paprika",
  "smoked-paprika",
  "chili-powder",
  "cinnamon",
  "cocoa",
  "matcha",
  "cajun-spice",
  "fajita-spice",
  "taco-spice",
  "shawarma-spice",
  "tikka-spice",
  "ras-el-hanout",
  "burger-bun",
  "butter",
  "ice-cream",
  "pizza-base"
] as const;

export type IngredientSlug = (typeof INGREDIENT_SLUGS)[number];

/** slug -> the curated name (today's lookup key) and the USDA food it resolves to. */
export const INGREDIENTS: Record<IngredientSlug, { name: string; fdcId: number }> = {
  "brown-rice": {
    "name": "brown rice",
    "fdcId": 169703
  },
  "rice": {
    "name": "rice",
    "fdcId": 169756
  },
  "cooked-rice": {
    "name": "cooked rice",
    "fdcId": 169704
  },
  "quinoa": {
    "name": "quinoa",
    "fdcId": 168874
  },
  "bulgur": {
    "name": "bulgur",
    "fdcId": 170688
  },
  "couscous": {
    "name": "couscous",
    "fdcId": 169699
  },
  "rolled-oats": {
    "name": "rolled oats",
    "fdcId": 173904
  },
  "oat-flour": {
    "name": "oat flour",
    "fdcId": 169741
  },
  "muesli": {
    "name": "muesli",
    "fdcId": 171646
  },
  "granola": {
    "name": "granola",
    "fdcId": 171646
  },
  "whole-wheat-pasta": {
    "name": "whole-wheat pasta",
    "fdcId": 169738
  },
  "whole-wheat-penne": {
    "name": "whole-wheat penne",
    "fdcId": 169738
  },
  "whole-wheat-spaghetti": {
    "name": "whole-wheat spaghetti",
    "fdcId": 169738
  },
  "orzo": {
    "name": "orzo",
    "fdcId": 169736
  },
  "egg-noodles": {
    "name": "egg noodles",
    "fdcId": 169731
  },
  "soba-noodles": {
    "name": "soba noodles",
    "fdcId": 168906
  },
  "rice-noodles": {
    "name": "rice noodles",
    "fdcId": 169742
  },
  "panko": {
    "name": "panko",
    "fdcId": 174928
  },
  "chickpea-flour": {
    "name": "chickpea flour",
    "fdcId": 174288
  },
  "chicken-breast": {
    "name": "chicken breast",
    "fdcId": 171077
  },
  "chicken-thigh": {
    "name": "chicken thigh",
    "fdcId": 173627
  },
  "turkey-breast": {
    "name": "turkey breast",
    "fdcId": 171098
  },
  "ground-turkey": {
    "name": "ground turkey",
    "fdcId": 172850
  },
  "turkey-sausage": {
    "name": "turkey sausage",
    "fdcId": 174617
  },
  "lean-beef": {
    "name": "lean beef",
    "fdcId": 171758
  },
  "lean-steak": {
    "name": "lean steak",
    "fdcId": 171758
  },
  "beef-strips": {
    "name": "beef strips",
    "fdcId": 171758
  },
  "lean-ground-beef": {
    "name": "lean ground beef",
    "fdcId": 173110
  },
  "lean-roast-beef": {
    "name": "lean roast beef",
    "fdcId": 171770
  },
  "pork-tenderloin": {
    "name": "pork tenderloin",
    "fdcId": 168249
  },
  "lean-pork-sausage": {
    "name": "lean pork sausage",
    "fdcId": 171631
  },
  "salmon-fillet": {
    "name": "salmon fillet",
    "fdcId": 175167
  },
  "smoked-salmon": {
    "name": "smoked salmon",
    "fdcId": 173687
  },
  "cod-fillet": {
    "name": "cod fillet",
    "fdcId": 171955
  },
  "canned-tuna": {
    "name": "canned tuna",
    "fdcId": 173709
  },
  "smoked-mackerel": {
    "name": "smoked mackerel",
    "fdcId": 175119
  },
  "smoked-trout": {
    "name": "smoked trout",
    "fdcId": 173717
  },
  "shrimp": {
    "name": "shrimp",
    "fdcId": 175179
  },
  "prawns": {
    "name": "prawns",
    "fdcId": 175179
  },
  "eggs": {
    "name": "eggs",
    "fdcId": 171287
  },
  "egg": {
    "name": "egg",
    "fdcId": 171287
  },
  "egg-whites": {
    "name": "egg whites",
    "fdcId": 172183
  },
  "firm-tofu": {
    "name": "firm tofu",
    "fdcId": 172448
  },
  "tempeh": {
    "name": "tempeh",
    "fdcId": 174272
  },
  "edamame": {
    "name": "edamame",
    "fdcId": 168411
  },
  "bean-sprouts": {
    "name": "bean sprouts",
    "fdcId": 169957
  },
  "chickpeas": {
    "name": "chickpeas",
    "fdcId": 173800
  },
  "black-beans": {
    "name": "black beans",
    "fdcId": 173735
  },
  "kidney-beans": {
    "name": "kidney beans",
    "fdcId": 173740
  },
  "cannellini-beans": {
    "name": "cannellini beans",
    "fdcId": 175203
  },
  "lentils": {
    "name": "lentils",
    "fdcId": 172421
  },
  "green-lentils": {
    "name": "green lentils",
    "fdcId": 172421
  },
  "red-lentils": {
    "name": "red lentils",
    "fdcId": 172420
  },
  "peas": {
    "name": "peas",
    "fdcId": 170016
  },
  "corn": {
    "name": "corn",
    "fdcId": 169214
  },
  "greek-yogurt": {
    "name": "greek yogurt",
    "fdcId": 170894
  },
  "yogurt": {
    "name": "yogurt",
    "fdcId": 170886
  },
  "milk": {
    "name": "milk",
    "fdcId": 171267
  },
  "cottage-cheese": {
    "name": "cottage cheese",
    "fdcId": 172182
  },
  "feta": {
    "name": "feta",
    "fdcId": 173420
  },
  "cheddar": {
    "name": "cheddar",
    "fdcId": 170899
  },
  "mozzarella": {
    "name": "mozzarella",
    "fdcId": 170847
  },
  "parmesan": {
    "name": "parmesan",
    "fdcId": 171247
  },
  "goat-cheese": {
    "name": "goat cheese",
    "fdcId": 173435
  },
  "halloumi": {
    "name": "halloumi",
    "fdcId": 170845
  },
  "ricotta": {
    "name": "ricotta",
    "fdcId": 171248
  },
  "cream-cheese": {
    "name": "cream cheese",
    "fdcId": 173418
  },
  "light-cream-cheese": {
    "name": "light cream cheese",
    "fdcId": 172207
  },
  "protein-powder": {
    "name": "protein powder",
    "fdcId": 173180
  },
  "soy-protein-powder": {
    "name": "soy protein powder",
    "fdcId": 173181
  },
  "spinach": {
    "name": "spinach",
    "fdcId": 168462
  },
  "kale": {
    "name": "kale",
    "fdcId": 168421
  },
  "rocket": {
    "name": "rocket",
    "fdcId": 169387
  },
  "romaine": {
    "name": "romaine",
    "fdcId": 169247
  },
  "lettuce": {
    "name": "lettuce",
    "fdcId": 169248
  },
  "mixed-greens": {
    "name": "mixed greens",
    "fdcId": 169249
  },
  "broccoli": {
    "name": "broccoli",
    "fdcId": 170379
  },
  "cauliflower": {
    "name": "cauliflower",
    "fdcId": 169986
  },
  "cabbage": {
    "name": "cabbage",
    "fdcId": 169975
  },
  "bok-choy": {
    "name": "bok choy",
    "fdcId": 170390
  },
  "pak-choi": {
    "name": "pak choi",
    "fdcId": 170390
  },
  "brussels-sprouts": {
    "name": "brussels sprouts",
    "fdcId": 170383
  },
  "asparagus": {
    "name": "asparagus",
    "fdcId": 168389
  },
  "green-beans": {
    "name": "green beans",
    "fdcId": 169961
  },
  "carrot": {
    "name": "carrot",
    "fdcId": 170393
  },
  "zucchini": {
    "name": "zucchini",
    "fdcId": 169291
  },
  "eggplant": {
    "name": "eggplant",
    "fdcId": 169228
  },
  "mushrooms": {
    "name": "mushrooms",
    "fdcId": 169251
  },
  "portobello-mushrooms": {
    "name": "portobello mushrooms",
    "fdcId": 169255
  },
  "bell-pepper": {
    "name": "bell pepper",
    "fdcId": 170108
  },
  "bell-peppers": {
    "name": "bell peppers",
    "fdcId": 170108
  },
  "roasted-peppers": {
    "name": "roasted peppers",
    "fdcId": 170108
  },
  "cucumber": {
    "name": "cucumber",
    "fdcId": 168409
  },
  "tomatoes": {
    "name": "tomatoes",
    "fdcId": 170457
  },
  "cherry-tomatoes": {
    "name": "cherry tomatoes",
    "fdcId": 170457
  },
  "chopped-tomatoes": {
    "name": "chopped tomatoes",
    "fdcId": 170051
  },
  "onion": {
    "name": "onion",
    "fdcId": 170000
  },
  "red-onion": {
    "name": "red onion",
    "fdcId": 170000
  },
  "garlic": {
    "name": "garlic",
    "fdcId": 169230
  },
  "sweet-potato": {
    "name": "sweet potato",
    "fdcId": 168482
  },
  "baby-potatoes": {
    "name": "baby potatoes",
    "fdcId": 170026
  },
  "beetroot": {
    "name": "beetroot",
    "fdcId": 169146
  },
  "cooked-beetroot": {
    "name": "cooked beetroot",
    "fdcId": 169146
  },
  "kimchi": {
    "name": "kimchi",
    "fdcId": 170392
  },
  "olives": {
    "name": "olives",
    "fdcId": 169094
  },
  "mixed-veg": {
    "name": "mixed veg",
    "fdcId": 170471
  },
  "mixed-stir-fry-veg": {
    "name": "mixed stir-fry veg",
    "fdcId": 170471
  },
  "roasted-vegetables": {
    "name": "roasted vegetables",
    "fdcId": 170471
  },
  "parsley": {
    "name": "parsley",
    "fdcId": 170416
  },
  "chives": {
    "name": "chives",
    "fdcId": 169994
  },
  "avocado": {
    "name": "avocado",
    "fdcId": 171705
  },
  "banana": {
    "name": "banana",
    "fdcId": 173944
  },
  "apple": {
    "name": "apple",
    "fdcId": 171688
  },
  "mango": {
    "name": "mango",
    "fdcId": 169910
  },
  "lemon": {
    "name": "lemon",
    "fdcId": 167746
  },
  "lime": {
    "name": "lime",
    "fdcId": 168155
  },
  "blueberries": {
    "name": "blueberries",
    "fdcId": 171711
  },
  "raspberries": {
    "name": "raspberries",
    "fdcId": 167755
  },
  "berries": {
    "name": "berries",
    "fdcId": 171711
  },
  "mixed-berries": {
    "name": "mixed berries",
    "fdcId": 171711
  },
  "frozen-berries": {
    "name": "frozen berries",
    "fdcId": 173950
  },
  "olive-oil": {
    "name": "olive oil",
    "fdcId": 171413
  },
  "sesame-oil": {
    "name": "sesame oil",
    "fdcId": 171016
  },
  "peanut-butter": {
    "name": "peanut butter",
    "fdcId": 172470
  },
  "almond-butter": {
    "name": "almond butter",
    "fdcId": 168588
  },
  "tahini": {
    "name": "tahini",
    "fdcId": 170189
  },
  "almonds": {
    "name": "almonds",
    "fdcId": 170567
  },
  "walnuts": {
    "name": "walnuts",
    "fdcId": 170187
  },
  "pecans": {
    "name": "pecans",
    "fdcId": 170182
  },
  "peanuts": {
    "name": "peanuts",
    "fdcId": 172430
  },
  "chia-seeds": {
    "name": "chia seeds",
    "fdcId": 170554
  },
  "sesame-seeds": {
    "name": "sesame seeds",
    "fdcId": 170150
  },
  "pumpkin-seeds": {
    "name": "pumpkin seeds",
    "fdcId": 170556
  },
  "sourdough-bread": {
    "name": "sourdough bread",
    "fdcId": 172686
  },
  "whole-grain-bread": {
    "name": "whole-grain bread",
    "fdcId": 172688
  },
  "whole-grain-toast": {
    "name": "whole-grain toast",
    "fdcId": 172689
  },
  "rye-bread": {
    "name": "rye bread",
    "fdcId": 172684
  },
  "wholegrain-bagel": {
    "name": "wholegrain bagel",
    "fdcId": 167533
  },
  "corn-tortillas": {
    "name": "corn tortillas",
    "fdcId": 175036
  },
  "tortillas": {
    "name": "tortillas",
    "fdcId": 175037
  },
  "whole-wheat-tortilla": {
    "name": "whole-wheat tortilla",
    "fdcId": 174081
  },
  "whole-wheat-wrap": {
    "name": "whole-wheat wrap",
    "fdcId": 174081
  },
  "honey": {
    "name": "honey",
    "fdcId": 169640
  },
  "hummus": {
    "name": "hummus",
    "fdcId": 174289
  },
  "pesto": {
    "name": "pesto",
    "fdcId": 171579
  },
  "salsa": {
    "name": "salsa",
    "fdcId": 174524
  },
  "tomato-sauce": {
    "name": "tomato sauce",
    "fdcId": 169074
  },
  "enchilada-sauce": {
    "name": "enchilada sauce",
    "fdcId": 169074
  },
  "tikka-masala-sauce": {
    "name": "tikka masala sauce",
    "fdcId": 169074
  },
  "buffalo-sauce": {
    "name": "buffalo sauce",
    "fdcId": 171186
  },
  "sriracha": {
    "name": "sriracha",
    "fdcId": 171186
  },
  "soy-sauce": {
    "name": "soy sauce",
    "fdcId": 174277
  },
  "teriyaki-sauce": {
    "name": "teriyaki sauce",
    "fdcId": 171167
  },
  "ginger-soy-sauce": {
    "name": "ginger-soy sauce",
    "fdcId": 171167
  },
  "soy-ginger-sauce": {
    "name": "soy-ginger sauce",
    "fdcId": 171167
  },
  "sesame-soy-sauce": {
    "name": "sesame-soy sauce",
    "fdcId": 171167
  },
  "tamarind-sauce": {
    "name": "tamarind sauce",
    "fdcId": 171167
  },
  "miso-paste": {
    "name": "miso paste",
    "fdcId": 172442
  },
  "harissa": {
    "name": "harissa",
    "fdcId": 171186
  },
  "horseradish": {
    "name": "horseradish",
    "fdcId": 173472
  },
  "light-caesar-dressing": {
    "name": "light caesar dressing",
    "fdcId": 169877
  },
  "curry-powder": {
    "name": "curry powder",
    "fdcId": 170924
  },
  "cumin": {
    "name": "cumin",
    "fdcId": 170923
  },
  "turmeric": {
    "name": "turmeric",
    "fdcId": 172231
  },
  "paprika": {
    "name": "paprika",
    "fdcId": 171329
  },
  "smoked-paprika": {
    "name": "smoked paprika",
    "fdcId": 171329
  },
  "chili-powder": {
    "name": "chili powder",
    "fdcId": 171319
  },
  "cinnamon": {
    "name": "cinnamon",
    "fdcId": 171320
  },
  "cocoa": {
    "name": "cocoa",
    "fdcId": 169593
  },
  "matcha": {
    "name": "matcha",
    "fdcId": 171917
  },
  "cajun-spice": {
    "name": "cajun spice",
    "fdcId": 171329
  },
  "fajita-spice": {
    "name": "fajita spice",
    "fdcId": 171319
  },
  "taco-spice": {
    "name": "taco spice",
    "fdcId": 171319
  },
  "shawarma-spice": {
    "name": "shawarma spice",
    "fdcId": 170923
  },
  "tikka-spice": {
    "name": "tikka spice",
    "fdcId": 170924
  },
  "ras-el-hanout": {
    "name": "ras el hanout",
    "fdcId": 170924
  },
  "burger-bun": {
    "name": "burger bun",
    "fdcId": 172796
  },
  "butter": {
    "name": "butter",
    "fdcId": 173410
  },
  "ice-cream": {
    "name": "ice cream",
    "fdcId": 167575
  },
  "pizza-base": {
    "name": "pizza base",
    "fdcId": 174924
  }
};
